var resultSummaryHtmlTemplate = function () {
    return [
      '<div class=\"popupResultSummaryPanel\">',
          '<div class="row">',
             '<span class="label">' + Localization.PopupResultSummaryAngleInfo + '</span>',
          '</div>',
          '<div class="row">',
              '<span class="label">',
                  '<table id="tablePopupResultSummaryPanel">',
                     '<tr><td>' + Localization.SAPSystem + '</td><td data-bind="text: SAPSystem"></td></tr>',
                     '<tr><td>' + Localization.ResultDateTime + '</td><td data-bind="text: resultDateTime"></td></tr>',
                  '</table>',
              '</span>',
          '</div>',
          '<div class="row">',
             '<span class="label">' + Localization.PopupResultSummaryResultInfo + '</span>',
          '</div>',
          '<div class="row">',
              '<span class="label">',
                  '<table id="tablePopupResultSummaryPanel">',
                     '<tr><td>' + Localization.BaseClassName + '</td><td  data-bind="html: baseClassName"></td></tr>',
                     '<tr><td>' + Localization.DisplayTotalRow + '</td><td data-bind="text: displayTotalRow"></td></tr>',
                     '<!-- ko if: displayModel.Data().display_type === enumHandlers.DISPLAYTYPE.PIVOT || displayModel.Data().display_type === enumHandlers.DISPLAYTYPE.CHART -->',
                     '<tr><td>' + Localization.NumberDataRows + '</td><td data-bind="text: totalRow"></td></tr>',
                     '<!-- /ko -->',
                     '<tr><td>' + Localization.ExecutionTime + '</td><td data-bind="text: executionTime"></td></tr>',
                     '<tr><td>' + Localization.ResponseTime + '</td><td data-bind="text: measurePerformance"></td></tr>',
                  '</table>',
              '</span>',
          '</div>',
          '<div class="row">',
             '<span class="label">' + Localization.PopupResultSummaryNote + '</span>',
          '</div>',
      '</div>'
    ].join('');
};
