var advanceFilterHtmlTemplate = function () {
    return [
        '<form autocomplete="off" onsubmit="return false">',
            '<div class="popupAdvFiltering">',
                '<div class="popupAdvFilteringRow popupAdvFilteringRowUsage">',
                    '<h2 class="popupSectionTitle">' + Localization.AdvanceFilterTextTitle + '</h2>',
                    '<div class="popupAdvFilteringContent">',
                        '<!-- ko if: searchPageHandler.CanEditId() -->',
                        '<div class="popupAdvFilteringItem">',
                            '<input type="text" class="input-light" autocomplete="off" id="ids" placeholder="' + Captions.Label_AdvanceFilter_AngleId + '" required />',
                        '</div>',
                        '<!-- /ko -->',
                        '<div class="popupAdvFilteringItem">',
                            '<input type="text" class="input-light" autocomplete="off" id="nameTextBox" placeholder="' + Captions.Label_AdvanceFilter_AngleName + '" required />',
                        '</div>',
                        '<div class="popupAdvFilteringItem">',
                            '<input type="text" class="input-light" autocomplete="off" id="descriptionTextBox" placeholder="' + Captions.Label_AdvanceFilter_AngleDescription + '" required />',
                        '</div>',
                    '</div>',
                    '<div class="popupAdvFilteringContent">',
                        '<div class="popupAdvFilteringItem">',
                            '<input type="text" class="input-light" autocomplete="off" id="displayNameTextBox" placeholder="' + Captions.Label_AdvanceFilter_AngleDisplayName + '" required />',
                        '</div>',
                        '<div class="popupAdvFilteringItem">',
                            '<input type="text" class="input-light" autocomplete="off" id="displayDescriptionTextBox" placeholder="' + Captions.Label_AdvanceFilter_DisplayDescription + '" required />',
                        '</div>',
                    '</div>',
                    '<div class="popupAdvFilteringContent">',
                        '<div class="popupAdvFilteringItem">',
                            '<input type="text" class="input-light" autocomplete="off" id="baseClassTextBox" placeholder="' + Captions.Label_AdvanceFilter_BaseClasses + '" required />',
                        '</div>',
                        '<div class="popupAdvFilteringItem">',
                            '<input type="text" class="input-light" autocomplete="off" id="queryStepFieldTextBox" placeholder="' + Captions.Label_AdvanceFilter_QueryStep + '" required />',
                        '</div>',
                        '<div class="popupAdvFilteringItem">',
                            '<input type="text" class="input-light" autocomplete="off" id="followupTextBox" placeholder="' + Captions.Label_AdvanceFilter_Followup + '" required />',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="popupAdvFilteringRow popupAdvFilteringRowUsage">',
                    '<h2 class="popupSectionTitle">' + Localization.AdvanceFilterUsageTitle + '</h2>',
                    '<div class="popupAdvFilteringContent createdFilter">',
                        '<div class="popupAdvFilteringItem">',
                            '<input class="k-autocomplete-light userFilter" id="createdFilter" placeholder="' + Localization.AdvanceFilterUsageCreateBy + '" required />',
                        '</div>',
                        '<div class="popupAdvFilteringItem">',
                            '<span class="k-dropdown-light dropdownUsageOperators createdFilterType" id="createdFilterType"></span>',
                        '</div>',
                        '<div class="popupAdvFilteringItem datepickerColumn">',
                            '<input type="text" class="Datepicker datepickerFrom" data-datepicker-class="k-datepicker-light datepickerFrom" id="createdFilterFrom" required />',
                        '</div>',
                        '<div class="popupAdvFilteringItem datepickerColumn">',
                            '<input type="text" class="Datepicker datepickerTo" data-datepicker-class="k-datepicker-light datepickerTo" id="createdFilterTo" required />',
                        '</div>',
                    '</div>',
                    '<div class="popupAdvFilteringContent lastChangedFilter">',
                        '<div class="popupAdvFilteringItem">',
                            '<input class="k-autocomplete-light userFilter" id="lastChangedFilter" placeholder="' + Captions.Label_AdvanceFilter_LastChangedBy + '" required />',
                        '</div>',
                        '<div class="popupAdvFilteringItem">',
                            '<span class="k-dropdown-light dropdownUsageOperators lastChangedFilterType" id="lastChangedFilterType"></span>',
                        '</div>',
                        '<div class="popupAdvFilteringItem datepickerColumn">',
                            '<input type="text" class="Datepicker datepickerFrom" data-datepicker-class="k-datepicker-light datepickerFrom" id="lastChangedFilterFrom" required />',
                         '</div>',
                        '<div class="popupAdvFilteringItem datepickerColumn">',
                            '<input type="text" class="Datepicker datepickerTo" data-datepicker-class="k-datepicker-light datepickerTo" id="lastChangedFilterTo" required />',
                        '</div>',
                    '</div>',
                    '<div class="popupAdvFilteringContent executeFilter">',
                        '<div class="popupAdvFilteringItem">',
                            '<input type="text" class="k-autocomplete-light userFilter" id="executeFilter" placeholder="' + Localization.AdvanceFilterUsageLastExecutedBy + '" required />',
                        '</div>',
                        '<div class="popupAdvFilteringItem">',
                            '<span class="k-dropdown-light dropdownUsageOperators executeFilterType" id="executeFilterType"></span>',
                        '</div>',
                        '<div class="popupAdvFilteringItem datepickerColumn">',
                            '<input type="text" class="Datepicker datepickerFrom" data-datepicker-class="k-datepicker-light datepickerFrom" id="executeFilterFrom" required />',
                        '</div>',
                        '<div class="popupAdvFilteringItem datepickerColumn">',
                            '<input type="text" class="Datepicker datepickerTo" data-datepicker-class="k-datepicker-light datepickerTo" id="executeFilterTo" required />',
                        '</div>',
                    '</div>',
                    '<div class="popupAdvFilteringContent validateFilter">',
                        '<div class="popupAdvFilteringItem">',
                            '<input type="text" class="k-autocomplete-light userFilter" id="validateFilter" placeholder="' + Localization.AdvanceFilterUsageValidationChangeBy + '" required />',
                        '</div>',
                        '<div class="popupAdvFilteringItem">',
                            '<span class="k-dropdown-light dropdownUsageOperators validateFilterType" id="validateFilterType"></span>',
                        '</div>',
                        '<div class="popupAdvFilteringItem datepickerColumn">',
                            '<input type="text" class="Datepicker datepickerFrom" data-datepicker-class="k-datepicker-light datepickerFrom" id="validateFilterFrom" required />',
                        '</div>',
                        '<div class="popupAdvFilteringItem datepickerColumn">',
                            '<input type="text" class="Datepicker datepickerTo" data-datepicker-class="k-datepicker-light datepickerTo" id="validateFilterTo" required />',
                        '</div>',
                    '</div>',
                    '<div class="popupAdvFilteringContent numberExecutedFilter">',
                        '<div class="popupAdvFilteringItem">',
                            '<span class="k-dropdown-light dropdownNumberExcutes" id="dropdownNumberExcutes"></span>',
                        '</div>',
                        '<div class="popupAdvFilteringItem">',
                            '<input type="text" class="k-numerictextbox-light" id="textNumberExcutes" placeholder="-" required />',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="popupAdvFilteringRow popupAdvFilteringRowLimitations">', 
                    '<div class="popupAdvFilteringContent">',
                        '<div class="popupAdvFilteringItem">',
                            '<label for="allowMoreDetailCheckbox">',
                                '<input type="checkbox" id="allowMoreDetailCheckbox" />',
                                '<span class="label" id="allowMoreDetailCheckboxLabel">' + Captions.Label_AdvanceFilter_Search_AllowMoreDetail + '</span>',
                            '</label>',
                        '</div>',
                        '<div class="popupAdvFilteringItem">',
                            '<label for="allowFollowUpCheckbox">',
                                '<input type="checkbox" id="allowFollowUpCheckbox" />',
                                '<span class="label" id="allowFollowUpCheckboxLabel">' + Captions.Label_AdvanceFilter_Search_AllowFollowup + '</span>',
                            '</label>',
                        '</div>',
                    '</div>',
                '</div>',
            '</div>',
        '</form>'
    ].join('');
};
