var advanceFilterHtmlTemplate = function () {
    var advanceFilterHtmlTemplate = "";
    advanceFilterHtmlTemplate += "<div class=\"popupAdvFiltering\">";
    advanceFilterHtmlTemplate += "    <div class=\"popupAdvFilteringRow popupAdvFilteringRowUsage\">";
    advanceFilterHtmlTemplate += "        <h2>" + Localization.AdvanceFilterUsageTitle + "<\/h2>";
    advanceFilterHtmlTemplate += "        <div class=\"popupAdvFilteringContent\">";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem createdFilter\">";
    advanceFilterHtmlTemplate += "                <label id=\"createdFilterLabel\">" + Localization.AdvanceFilterUsageCreateBy + ":<\/label>";
    advanceFilterHtmlTemplate += "                <input class=\"eaAutocomplete eaAutocompleteSize40 userFilter\" id=\"createdFilter\" \/>";
    advanceFilterHtmlTemplate += "                <span class=\"eaDropdown eaDropdownSize40 dropdownUsageOperators createdFilterType\" id=\"createdFilterType\"><\/span>";
    advanceFilterHtmlTemplate += "                <label class=\"labelSmall\"><\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" class=\"Datepicker datepickerFrom\" data-datepicker-class=\"eaDatepicker eaDatepickerSize40 datepickerFrom\" id=\"createdFilterFrom\" \/>";
    advanceFilterHtmlTemplate += "                <label class=\"labelSmall\"><\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" class=\"Datepicker datepickerTo\" data-datepicker-class=\"eaDatepicker eaDatepickerSize40 datepickerTo\" id=\"createdFilterTo\" \/>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem lastChangedFilter\">";
    advanceFilterHtmlTemplate += "                <label id=\"lastChangedFilterLabel\">" + Captions.Label_AdvanceFilter_LastChangedBy + ":<\/label>";
    advanceFilterHtmlTemplate += "                <input class=\"eaAutocomplete eaAutocompleteSize40 userFilter\" id=\"lastChangedFilter\" \/>";
    advanceFilterHtmlTemplate += "                <span class=\"eaDropdown eaDropdownSize40 dropdownUsageOperators lastChangedFilterType\" id=\"lastChangedFilterType\"><\/span>";
    advanceFilterHtmlTemplate += "                <label class=\"labelSmall\"><\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" class=\"Datepicker datepickerFrom\" data-datepicker-class=\"eaDatepicker eaDatepickerSize40 datepickerFrom\" id=\"lastChangedFilterFrom\" \/>";
    advanceFilterHtmlTemplate += "                <label class=\"labelSmall\"><\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" class=\"Datepicker datepickerTo\" data-datepicker-class=\"eaDatepicker eaDatepickerSize40 datepickerTo\" id=\"lastChangedFilterTo\" \/>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem executeFilter\">";
    advanceFilterHtmlTemplate += "                <label id=\"executeFilterLabel\">" + Localization.AdvanceFilterUsageLastExecutedBy + ":<\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" class=\"eaAutocomplete eaAutocompleteSize40 userFilter\" id=\"executeFilter\" \/>";
    advanceFilterHtmlTemplate += "                <span class=\"eaDropdown eaDropdownSize40 dropdownUsageOperators executeFilterType\" id=\"executeFilterType\"><\/span>";
    advanceFilterHtmlTemplate += "                <label class=\"labelSmall\"><\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" class=\"Datepicker datepickerFrom\" data-datepicker-class=\"eaDatepicker eaDatepickerSize40 datepickerFrom\" id=\"executeFilterFrom\" \/>";
    advanceFilterHtmlTemplate += "                <label class=\"labelSmall\"><\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" class=\"Datepicker datepickerTo\" data-datepicker-class=\"eaDatepicker eaDatepickerSize40 datepickerTo\" id=\"executeFilterTo\" \/>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem validateFilter\">";
    advanceFilterHtmlTemplate += "                <label id=\"validateFilterLabel\">" + Localization.AdvanceFilterUsageValidationChangeBy + ":<\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" class=\"eaAutocomplete eaAutocompleteSize40 userFilter\" id=\"validateFilter\" \/>";
    advanceFilterHtmlTemplate += "                <span class=\"eaDropdown eaDropdownSize40 dropdownUsageOperators validateFilterType\" id=\"validateFilterType\"><\/span>";
    advanceFilterHtmlTemplate += "                <label class=\"labelSmall\"><\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" class=\"Datepicker datepickerFrom\" data-datepicker-class=\"eaDatepicker eaDatepickerSize40 datepickerFrom\" id=\"validateFilterFrom\" \/>";
    advanceFilterHtmlTemplate += "                <label class=\"labelSmall\"><\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" class=\"Datepicker datepickerTo\" data-datepicker-class=\"eaDatepicker eaDatepickerSize40 datepickerTo\" id=\"validateFilterTo\" \/>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem numberExecutedFilter\">";
    advanceFilterHtmlTemplate += "                <label id=\"numberExcutesLabel\">" + Localization.AdvanceFilterUsageNumberOfExecutes + ":<\/label>";
    advanceFilterHtmlTemplate += "                <span class=\"eaDropdown eaDropdownSize40 dropdownNumberExcutes\" id=\"dropdownNumberExcutes\"><\/span>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" class=\"eaNumeric eaNumericSize40 \" id=\"textNumberExcutes\" \/>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "           <div class=\"popupAdvFilteringItem publicStatus\">";
    advanceFilterHtmlTemplate += "                <label id=\"publicStatusLabel\">" + Captions.Label_AdvanceFilter_PulicationStatus + ":<\/label>";
    advanceFilterHtmlTemplate += "                <span class=\"eaDropdown eaDropdownSize40 dropdownPublicStatus\" id=\"dropdownPublicStatus\"><\/span>";
    advanceFilterHtmlTemplate += "              ";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem validationStatus\">";
    advanceFilterHtmlTemplate += "                <label id=\"validationLabel\">" + Captions.Label_AdvanceFilter_ValidationStatus + ":<\/label>";
    advanceFilterHtmlTemplate += "                <span class=\"eaDropdown eaDropdownSize40 dropdownValidation\" id=\"dropdownValidation\"><\/span>";
    advanceFilterHtmlTemplate += "              ";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem warningStatus\">";
    advanceFilterHtmlTemplate += "                <label id=\"starredLabel\">" + Captions.Label_AdvanceFilter_WarningStatus + ":<\/label>";
    advanceFilterHtmlTemplate += "                <span class=\"eaDropdown eaDropdownSize40 dropdownWarning\" id=\"dropdownWarning\"><\/span>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem starredStatus\">";
    advanceFilterHtmlTemplate += "                <label id=\"starredLabel\">" + Captions.Label_AdvanceFilter_StarredStatus + ":<\/label>";
    advanceFilterHtmlTemplate += "                <span class=\"eaDropdown eaDropdownSize40 dropdownStarred\" id=\"dropdownStarred\"><\/span>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "        <\/div>";
    advanceFilterHtmlTemplate += "    <\/div>";
    advanceFilterHtmlTemplate += "    <div class=\"popupAdvFilteringRow popupAdvFilteringRowUsage\">";
    advanceFilterHtmlTemplate += "        <h2>" + Localization.AdvanceFilterTextTitle + "<\/h2>";
    advanceFilterHtmlTemplate += "        <div class=\"popupAdvFilteringContent\">";

    advanceFilterHtmlTemplate += "        <!-- ko if: searchPageHandler.CanEditId() -->";
    advanceFilterHtmlTemplate += "        <div class=\"popupAdvFilteringItem\">";
    advanceFilterHtmlTemplate += "            <label id=\"idsLabel\">" + Captions.Label_AdvanceFilter_AngleId + "<\/label>";
    advanceFilterHtmlTemplate += "            <input type=\"text\" style='width:270px' class=\"eaText eaTextSize40\" id=\"ids\"\/>";
    advanceFilterHtmlTemplate += "        <\/div>";
    advanceFilterHtmlTemplate += "        <!-- /ko -->";

    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem\">";
    advanceFilterHtmlTemplate += "                <label id=\"nameTextBoxLabel\">" + Captions.Label_AdvanceFilter_AngleName + "<\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" style='width:270px' class=\"eaText eaTextSize40\" id=\"nameTextBox\"\/>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem\">";
    advanceFilterHtmlTemplate += "                <label id=\"descriptionTextBoxLabel\">" + Captions.Label_AdvanceFilter_AngleDescription + "<\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" style='width:270px' class=\"eaText eaTextSize40\" id=\"descriptionTextBox\" \/>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem\">";
    advanceFilterHtmlTemplate += "                <label id=\"displayNameTextBoxLabel\">" + Captions.Label_AdvanceFilter_AngleDisplayName + "<\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" style='width:270px' class=\"eaText eaTextSize40\" id=\"displayNameTextBox\" \/>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem\">";
    advanceFilterHtmlTemplate += "                <label id=\"displayDescriptionTextBoxLabel\">" + Captions.Label_AdvanceFilter_DisplayDescription + "<\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" style='width:270px' class=\"eaText eaTextSize40\"  id=\"displayDescriptionTextBox\" \/>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem\">";
    advanceFilterHtmlTemplate += "                <label id=\"baseClassTextBoxLabel\">" + Captions.Label_AdvanceFilter_BaseClasses + "<\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" style='width:270px' class=\"eaText eaTextSize40\" id=\"baseClassTextBox\" \/>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem\">";
    advanceFilterHtmlTemplate += "                <label id=\"queryStepFieldTextBoxLabel\">" + Captions.Label_AdvanceFilter_QueryStep + "<\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" style='width:270px' class=\"eaText eaTextSize40\" id=\"queryStepFieldTextBox\" \/>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem\">";
    advanceFilterHtmlTemplate += "                <label id=\"followupTextBoxLabel\">" + Captions.Label_AdvanceFilter_Followup + "<\/label>";
    advanceFilterHtmlTemplate += "                <input type=\"text\" style='width:270px' class=\"eaText eaTextSize40\" id=\"followupTextBox\"\/>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "        <\/div>";
    advanceFilterHtmlTemplate += "    <\/div>";
    advanceFilterHtmlTemplate += "    <div class=\"popupAdvFilteringRow popupAdvFilteringRowLimitations\">";
    advanceFilterHtmlTemplate += "        <h2>" + Localization.AdvanceFilterLimitationsTitle + "<\/h2>";
    advanceFilterHtmlTemplate += "        <div class=\"popupAdvFilteringContent\">";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem\">";
    advanceFilterHtmlTemplate += "                <label for=\"allowMoreDetailCheckbox\">";
    advanceFilterHtmlTemplate += "                    <input type=\"checkbox\" id=\"allowMoreDetailCheckbox\" \/>";
    advanceFilterHtmlTemplate += "                    <span class=\"label\" id=\"allowMoreDetailCheckboxLabel\">" + Captions.Label_AdvanceFilter_Search_AllowMoreDetail + "<\/span>";
    advanceFilterHtmlTemplate += "                <\/label>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "            <div class=\"popupAdvFilteringItem\">";
    advanceFilterHtmlTemplate += "                <label for=\"allowFollowUpCheckbox\">";
    advanceFilterHtmlTemplate += "                    <input type=\"checkbox\" id=\"allowFollowUpCheckbox\" \/>";
    advanceFilterHtmlTemplate += "                    <span class=\"label\" id=\"allowFollowUpCheckboxLabel\">" + Captions.Label_AdvanceFilter_Search_AllowFollowup + "<\/span>";
    advanceFilterHtmlTemplate += "                <\/label>";
    advanceFilterHtmlTemplate += "            <\/div>";
    advanceFilterHtmlTemplate += "        <\/div>";
    advanceFilterHtmlTemplate += "    <\/div>";
    advanceFilterHtmlTemplate += "<\/div>";
    return advanceFilterHtmlTemplate;
};
