#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/LoginPage.cshtml")]
    public partial class _Views_User_LoginPage_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_User_LoginPage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<form");

WriteLiteral(" id=\"LoginForm\"");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 34), Tuple.Create("\"", 62)
            
            #line 1 "..\..\Views\User\LoginPage.cshtml"
, Tuple.Create(Tuple.Create("", 43), Tuple.Create<System.Object, System.Int32>(ViewBag.PostAction
            
            #line default
            #line hidden
, 43), false)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"LoginContainer\"");

WriteLiteral(">\r\n        <h1>");

            
            #line 3 "..\..\Views\User\LoginPage.cshtml"
       Write(EveryAngle.Shared.Globalization.Resource.Login);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n        <input");

WriteLiteral(" id=\"UserName\"");

WriteLiteral(" name=\"wc_username\"");

WriteLiteral(" class=\"UserName\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" tabindex=\"1\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 261), Tuple.Create("\"", 325)
            
            #line 4 "..\..\Views\User\LoginPage.cshtml"
                                 , Tuple.Create(Tuple.Create("", 275), Tuple.Create<System.Object, System.Int32>(EveryAngle.Shared.Globalization.Resource.Username
            
            #line default
            #line hidden
, 275), false)
);

WriteLiteral(" />\r\n        <input");

WriteLiteral(" id=\"Password\"");

WriteLiteral(" name=\"wc_password\"");

WriteLiteral(" class=\"Password\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" tabindex=\"2\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 433), Tuple.Create("\"", 497)
            
            #line 5 "..\..\Views\User\LoginPage.cshtml"
                                     , Tuple.Create(Tuple.Create("", 447), Tuple.Create<System.Object, System.Int32>(EveryAngle.Shared.Globalization.Resource.Password
            
            #line default
            #line hidden
, 447), false)
);

WriteLiteral(" />\r\n        \r\n        <div");

WriteLiteral(" class=\"ChangePaswordSection ChangePassword\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" id=\"oldPassword\"");

WriteLiteral(" name=\"wc_oldPassword\"");

WriteLiteral(" class=\"Password oldPassword\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" tabindex=\"2\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 687), Tuple.Create("\"", 754)
            
            #line 8 "..\..\Views\User\LoginPage.cshtml"
                                                  , Tuple.Create(Tuple.Create("", 701), Tuple.Create<System.Object, System.Int32>(EveryAngle.Shared.Globalization.Resource.OldPassword
            
            #line default
            #line hidden
, 701), false)
);

WriteLiteral(" />\r\n            <input");

WriteLiteral(" id=\"newPassword\"");

WriteLiteral(" name=\"wc_newPassword\"");

WriteLiteral(" class=\"Password newPassword\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" tabindex=\"3\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 875), Tuple.Create("\"", 942)
            
            #line 9 "..\..\Views\User\LoginPage.cshtml"
                                                  , Tuple.Create(Tuple.Create("", 889), Tuple.Create<System.Object, System.Int32>(EveryAngle.Shared.Globalization.Resource.NewPassword
            
            #line default
            #line hidden
, 889), false)
);

WriteLiteral(" />\r\n            <input");

WriteLiteral(" id=\"ComparedPassword\"");

WriteLiteral(" name=\"wc_newComparedPassword\"");

WriteLiteral(" class=\"Password ComparedPassword\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" tabindex=\"4\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 1081), Tuple.Create("\"", 1152)
            
            #line 10 "..\..\Views\User\LoginPage.cshtml"
                                                                   , Tuple.Create(Tuple.Create("", 1095), Tuple.Create<System.Object, System.Int32>(EveryAngle.Shared.Globalization.Resource.ConfirmPassword
            
            #line default
            #line hidden
, 1095), false)
);

WriteLiteral(" />\r\n            <input");

WriteLiteral(" id=\"ChangePasswordButton\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" type=\"button\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1239), Tuple.Create("\"", 1303)
            
            #line 11 "..\..\Views\User\LoginPage.cshtml"
         , Tuple.Create(Tuple.Create("", 1247), Tuple.Create<System.Object, System.Int32>(EveryAngle.Shared.Globalization.Resource.ChangePassword
            
            #line default
            #line hidden
, 1247), false)
);

WriteLiteral("  tabindex=\"5\"");

WriteLiteral(" />\r\n            <a");

WriteLiteral(" id=\"CancelButtonPassword\"");

WriteLiteral(">");

            
            #line 12 "..\..\Views\User\LoginPage.cshtml"
                                    Write(EveryAngle.Shared.Globalization.Resource.Cancel);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        </div>\r\n\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"LogoContainer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"Logo LogoImage\"");

WriteLiteral("></div>\r\n        </div>\r\n        <input");

WriteLiteral(" id=\"LoginButton\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" type=\"button\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1724), Tuple.Create("\"", 1779)
            
            #line 19 "..\..\Views\User\LoginPage.cshtml"
, Tuple.Create(Tuple.Create("", 1732), Tuple.Create<System.Object, System.Int32>(EveryAngle.Shared.Globalization.Resource.Login
            
            #line default
            #line hidden
, 1732), false)
);

WriteLiteral(" tabindex=\"3\"");

WriteLiteral(" />\r\n\r\n        <a");

WriteLiteral(" id=\"CancelButton\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\User\LoginPage.cshtml"
                                               Write(EveryAngle.Shared.Globalization.Resource.Cancel);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        <div");

WriteLiteral(" class=\"loginLoading\"");

WriteLiteral("></div>\r\n\r\n        <div");

WriteLiteral(" id=\"ErrorMessage\"");

WriteLiteral(" class=\"loginMessage\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"SessonExpiredDetail\"");

WriteLiteral("></div>\r\n\r\n\r\n\r\n    </div>\r\n</form>\r\n");

        }
    }
}
#pragma warning restore 1591
