#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/PartialViews/UserLoginBodyPage.cshtml")]
    public partial class _Views_User_PartialViews_UserLoginBodyPage_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_User_PartialViews_UserLoginBodyPage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"LoginContainer\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 2 "..\..\Views\User\PartialViews\UserLoginBodyPage.cshtml"
   Write(EveryAngle.Shared.Globalization.Resource.Login);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n    <input");

WriteLiteral(" id=\"UserName\"");

WriteLiteral(" name=\"wc_username\"");

WriteLiteral(" class=\"UserName\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" tabindex=\"1\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 174), Tuple.Create("\"", 238)
            
            #line 3 "..\..\Views\User\PartialViews\UserLoginBodyPage.cshtml"
                    , Tuple.Create(Tuple.Create("", 188), Tuple.Create<System.Object, System.Int32>(EveryAngle.Shared.Globalization.Resource.Username
            
            #line default
            #line hidden
, 188), false)
);

WriteLiteral(" />\r\n    <input");

WriteLiteral(" id=\"Password\"");

WriteLiteral(" name=\"wc_password\"");

WriteLiteral(" class=\"Password\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" tabindex=\"2\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 333), Tuple.Create("\"", 397)
            
            #line 4 "..\..\Views\User\PartialViews\UserLoginBodyPage.cshtml"
                        , Tuple.Create(Tuple.Create("", 347), Tuple.Create<System.Object, System.Int32>(EveryAngle.Shared.Globalization.Resource.Password
            
            #line default
            #line hidden
, 347), false)
);

WriteLiteral(" />\r\n\r\n    <div");

WriteLiteral(" class=\"LogoContainer\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"Logo LogoImage\"");

WriteLiteral("></div>\r\n    </div>\r\n    <input");

WriteLiteral(" id=\"LoginButton\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" type=\"button\"");

WriteAttribute("value", Tuple.Create(" value=\"", 559), Tuple.Create("\"", 614)
            
            #line 9 "..\..\Views\User\PartialViews\UserLoginBodyPage.cshtml"
, Tuple.Create(Tuple.Create("", 567), Tuple.Create<System.Object, System.Int32>(EveryAngle.Shared.Globalization.Resource.Login
            
            #line default
            #line hidden
, 567), false)
);

WriteLiteral(" tabindex=\"3\"");

WriteLiteral(" />\r\n\r\n    <a");

WriteLiteral(" id=\"CancelButton\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">");

            
            #line 11 "..\..\Views\User\PartialViews\UserLoginBodyPage.cshtml"
                                           Write(EveryAngle.Shared.Globalization.Resource.Cancel);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n    <div");

WriteLiteral(" class=\"loginLoading\"");

WriteLiteral("></div>\r\n\r\n    <div");

WriteLiteral(" id=\"ErrorMessage\"");

WriteLiteral(" class=\"loginMessage\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"SessonExpiredDetail\"");

WriteLiteral("></div>\r\n    <span");

WriteLiteral(" id=\"VersionInfoLogin\"");

WriteLiteral(" class=\"VersionInfo\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\User\PartialViews\UserLoginBodyPage.cshtml"
                                               Write(ViewBag.FileVersion);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    jQuery(""#UserName, #Password"").off('keypress').on('keypress', function (event) {
        if (event.which == 13 && window.UserLogin) {
            window.UserLogin(jQuery('#UserName').val(), jQuery('#Password').val());
        }
    });
    jQuery('#LoginButton').removeAttr('onclick').off('click').on('click', function (event) {
        if (window.UserLogin) {
            UserLogin(jQuery('#UserName').val(), jQuery('#Password').val());
        }
    });
    jQuery('#CancelButton').removeAttr('onclick').off('click').on('click', function (event) {
        if (window.CancelToLoginPage) {
            window.CancelToLoginPage();
        }
    });
</script>
");

        }
    }
}
#pragma warning restore 1591
