var customeSortHtmlTemplate = function () {
    return [
        '<div class="label"><span class="sortNumber">1</span>' + Captions.Label_Sort_By + '</div>',
        '<div class="field">',
            '<select class="k-dropdown" id="CustomSortField1"></select>',
            '<label>',
                '<input type="radio" name="sort1" value="ASC" checked="checked" />',
                '<span class="label inline">' + Captions.Label_Sort_Ascending + '</span>',
            '</label>',
            '<label>',
                '<input type="radio" name="sort1" value="DESC" />',
                '<span class="label">' + Captions.Label_Sort_Descending + '</span>',
            '</label>',
        '</div>',
        '<div class="StatSeparate"></div>',
        '<div class="label"><span class="sortNumber">2</span>' + Captions.Label_Sort_ThenBy + '</div>',
        '<div class="field">',
            '<select class="k-dropdown" id="CustomSortField2"></select>',
            '<label>',
                '<input type="radio" name="sort2" value="ASC" checked="checked" />',
                '<span class="label inline">' + Captions.Label_Sort_Ascending + '</span>',
            '</label>',
            '<label>',
                '<input type="radio" name="sort2" value="DESC" />',
                '<span class="label">' + Captions.Label_Sort_Descending + '</span>',
            '</label>',
        '</div>',
        '<div class="StatSeparate"></div>',
        '<div class="label"><span class="sortNumber">3</span>' + Captions.Label_Sort_ThenBy + '</div>',
        '<div class="field">',
            '<select class="k-dropdown" id="CustomSortField2"></select>',
            '<label>',
                '<input type="radio" name="sort3" value="ASC" checked="checked" />',
                '<span class="label inline">' + Captions.Label_Sort_Ascending + '</span>',
            '</label>',
            '<label>',
                '<input type="radio" name="sort3" value="DESC" />',
                '<span class="label">' + Captions.Label_Sort_Descending + '</span>',
            '</label>',
        '</div>'
    ].join('');
};
