var createAngleOptionHtmlTemplate = function () {
    var createAngleOptionHtmlTemplate = "";
    createAngleOptionHtmlTemplate += "<div id=\"ChooseNewAngleOption\" class=\"contentContainer\">";
    createAngleOptionHtmlTemplate += "    <div class=\"content\">";
    createAngleOptionHtmlTemplate += "        <div class=\"imageSection\">";
    createAngleOptionHtmlTemplate += "            <img alt=\"" + Localization.CreateFromSchemaSimple + "\" onclick=\"createNewAngleViewManagementModel.ShowCreateAngleBySchema(createNewAngleViewManagementModel.SCHEMAVIEWTYPE.SIMPLE);\" height=\"122\" width=\"167\" \/>";
    createAngleOptionHtmlTemplate += "        <\/div>";
    createAngleOptionHtmlTemplate += "        <div class=\"contentSection\">";
    createAngleOptionHtmlTemplate += "            <h2>" + Localization.CreateFromSchemaSimple + "<\/h2>";
    createAngleOptionHtmlTemplate += "            <p>" + Localization.CreateFromSchemaSimpleDescription + "<\/p>";
    createAngleOptionHtmlTemplate += "            <div class=\"buttonContainer\">";
    createAngleOptionHtmlTemplate += "                <div class=\"showObjectButton\">";
    createAngleOptionHtmlTemplate += "                    <a class=\"btn btn-ghost float-right btnCreateFromSchema\" id=\"ButtonCreateAngleFromSchemaSimple\" onclick=\"createNewAngleViewManagementModel.ShowCreateAngleBySchema(createNewAngleViewManagementModel.SCHEMAVIEWTYPE.SIMPLE);\"><span>" + Captions.Button_Continue + "<\/span><\/a>";
    createAngleOptionHtmlTemplate += "                <\/div>";
    createAngleOptionHtmlTemplate += "            <\/div>";
    createAngleOptionHtmlTemplate += "        <\/div>";
    createAngleOptionHtmlTemplate += "    <\/div>";
    createAngleOptionHtmlTemplate += "    <div class=\"content\">";
    createAngleOptionHtmlTemplate += "        <div class=\"imageSection\">";
    createAngleOptionHtmlTemplate += "            <img alt=\"" + Localization.CreateFromSchemaDetailed + "\" onclick=\"createNewAngleViewManagementModel.ShowCreateAngleBySchema(createNewAngleViewManagementModel.SCHEMAVIEWTYPE.DETAILED)\" height=\"122\" width=\"167\" \/>";
    createAngleOptionHtmlTemplate += "        <\/div>";
    createAngleOptionHtmlTemplate += "        <div class=\"contentSection\">";
    createAngleOptionHtmlTemplate += "            <h2>" + Localization.CreateFromSchemaDetailed + "<\/h2>";
    createAngleOptionHtmlTemplate += "            <p>" + Localization.CreateFromSchemaDetailedDescription + "<\/p>";
    createAngleOptionHtmlTemplate += "            <div class=\"buttonContainer\">";
    createAngleOptionHtmlTemplate += "                <div class=\"showObjectButton\">";
    createAngleOptionHtmlTemplate += "                    <a class=\"btn btn-ghost float-right btnCreateFromSchema\" id=\"ButtonCreateAngleFromSchemaDetailed\" onclick=\"createNewAngleViewManagementModel.ShowCreateAngleBySchema(createNewAngleViewManagementModel.SCHEMAVIEWTYPE.DETAILED)\"><span>" + Captions.Button_Continue + "<\/span><\/a>";
    createAngleOptionHtmlTemplate += "                <\/div>";
    createAngleOptionHtmlTemplate += "            <\/div>";
    createAngleOptionHtmlTemplate += "        <\/div>";
    createAngleOptionHtmlTemplate += "    <\/div>";
    createAngleOptionHtmlTemplate += "    <div class=\"content\">";
    createAngleOptionHtmlTemplate += "        <div class=\"imageSection\">";
    createAngleOptionHtmlTemplate += "            <img alt=\"" + Localization.CreateFromObjects + "\" src=\"" + GetImageFolderPath() + "angle\/create_new_full_list.png\" onclick=\"createNewAngleViewManagementModel.ShowCreateAngleByObject()\" height=\"122\" width=\"167\"\/>";
    createAngleOptionHtmlTemplate += "        <\/div>";
    createAngleOptionHtmlTemplate += "        <div class=\"contentSection\">";
    createAngleOptionHtmlTemplate += "            <h2>" + Localization.CreateFromObjects + "<\/h2>";
    createAngleOptionHtmlTemplate += "            <p>" + Localization.CreateFromObjectsDescription + "<\/p>";
    createAngleOptionHtmlTemplate += "            <div class=\"buttonContainer\">";
    createAngleOptionHtmlTemplate += "                <div class=\"showObjectButton\">";
    createAngleOptionHtmlTemplate += "                    <a class=\"btn btn-ghost float-right btnCreateFromObject\" id=\"ButtonCreateAngleFromObjects\" onclick=\"createNewAngleViewManagementModel.ShowCreateAngleByObject()\"><span>" + Captions.Button_Continue + "<\/span><\/a>";
    createAngleOptionHtmlTemplate += "                <\/div>";
    createAngleOptionHtmlTemplate += "            <\/div>";
    createAngleOptionHtmlTemplate += "        <\/div>";
    createAngleOptionHtmlTemplate += "    <\/div>";
    createAngleOptionHtmlTemplate += "<\/div>";

    return createAngleOptionHtmlTemplate;
};
