var findAngleResultHtmlTemplate = function () {
    return [
        '<div id="findPopupArea">',
            '<div class="findPopupOption findPopupOptionText">',
                '<label data-bind="text: Localization.FindAngleResultTextToFind"></label>',
                '<input id="findText" type="text" class="eaText"/>',
            '</div>',
            '<fieldset class="findPopupOption findPopupOptionOther">',
                '<legend data-bind="text: Localization.FindAngleResultOptions"></legend>',
                '<div>',
                    '<label>',
                        '<input id="caseSensitive" type="checkbox"/>',
                        '<span class="label" data-bind="text: Localization.FindAngleResultCaseSensitive"></span>',
                    '</label>',
                '</div>',
            '</fieldset>',
            '<fieldset class="findPopupOption findPopupOptionScope">',
                '<legend data-bind="text: Localization.FindAngleResultScope"></legend>',
                '<div>',
                    '<label>',
                        '<input id="allTextFind" type="radio" name="scope" onclick="anglePageHandler.HandlerFind.ToggleFieldDropdownList({ Status: false });" checked />',
                        '<span class="label" data-bind="text: Localization.FindAngleResultAllTextField"></span>',
                    '</label>',
                '</div>',
                '<div>',
                    '<label>',
                        '<input id="selectTextFind" type="radio" name="scope" onclick="anglePageHandler.HandlerFind.ToggleFieldDropdownList({ Status: true });" />',
                        '<span class="label" data-bind="text: Localization.FindAngleResultSelectedTextField"></span>',
                        '<br />',
                    '</label>',
                '</div>',
                '<div>',
                    '<input id="fieldDropdownList" class="eaDropdown" />',
                '</div>',
            '</fieldset>',
            '<fieldset class="findPopupOption findPopupOptionDirection">',
                '<legend data-bind="text: Localization.FindAngleResultDirection"></legend>',
                '<div>',
                    '<label>',
                        '<input id="directionForward" type="radio" name="direction" checked />',
                        '<span class="label" data-bind="text: Localization.FindAngleResultForward"></span>',
                    '</label>',
                '</div>',
                '<div>',
                    '<label>',
                        '<input id="directionBackward" type="radio" name="direction" />',
                        '<span class="label" data-bind="text: Localization.FindAngleResultBackward"></span>',
                    '</label>',
                '</div>',
            '</fieldset>',
            '<fieldset class="findPopupOption findPopupOptionOrigin">',
                '<legend data-bind="text: Localization.FindAngleResultOrigin"></legend>',
                '<div>',
                    '<label>',
                        '<input id="originCursor" type="radio" name="origin" checked/>',
                        '<span class="label" data-bind="text: Localization.FindAngleResultFromCursor"></span>',
                    '</label>',
                '</div>',
                '<div>',
                    '<label>',
                        '<input id="originScope" type="radio" name="origin" />',
                        '<span class="label" data-bind="text: Localization.FindAngleResultEntireScope"></span>',
                    '</label>',
                '</div>',
            '</fieldset>',
        '</div>'
    ].join('');
}
