//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveryAngle.Shared.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Captions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Captions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EveryAngle.Shared.Globalization.Captions", typeof(Captions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available for ad hoc Display.
        /// </summary>
        public static string AdhocEnableSummarySheet {
            get {
                return ResourceManager.GetString("AdhocEnableSummarySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download individual Angles.
        /// </summary>
        public static string AngleExport_TypeDownload {
            get {
                return ResourceManager.GetString("AngleExport_TypeDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Angles as a package.
        /// </summary>
        public static string AngleExport_TypePackage {
            get {
                return ResourceManager.GetString("AngleExport_TypePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to previous page.
        /// </summary>
        public static string Button_BackToPreviousPage {
            get {
                return ResourceManager.GetString("Button_BackToPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel execution.
        /// </summary>
        public static string Button_CancelExecution {
            get {
                return ResourceManager.GetString("Button_CancelExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Button_ChartOptions {
            get {
                return ResourceManager.GetString("Button_ChartOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Angle.
        /// </summary>
        public static string Button_CreateNewAngle {
            get {
                return ResourceManager.GetString("Button_CreateNewAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No model.
        /// </summary>
        public static string Button_CreateNewAngle_NoModel {
            get {
                return ResourceManager.GetString("Button_CreateNewAngle_NoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Dashboard_WidgetDelete {
            get {
                return ResourceManager.GetString("Button_Dashboard_WidgetDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit title.
        /// </summary>
        public static string Button_Dashboard_WidgetEditTitle {
            get {
                return ResourceManager.GetString("Button_Dashboard_WidgetEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Angle.
        /// </summary>
        public static string Button_Dashboard_WidgetGotoAngle {
            get {
                return ResourceManager.GetString("Button_Dashboard_WidgetGotoAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Button_Dashboard_WidgetMaximize {
            get {
                return ResourceManager.GetString("Button_Dashboard_WidgetMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Button_Dashboard_WidgetMinimize {
            get {
                return ResourceManager.GetString("Button_Dashboard_WidgetMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_EditItem {
            get {
                return ResourceManager.GetString("Button_EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request could not be processed because of a conflict in the request..
        /// </summary>
        public static string Conflict_Header_Message {
            get {
                return ResourceManager.GetString("Conflict_Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop here to remove this column.
        /// </summary>
        public static string Drop_Here_To_Remove_This_Column {
            get {
                return ResourceManager.GetString("Drop_Here_To_Remove_This_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string FieldFormat_Example {
            get {
                return ResourceManager.GetString("FieldFormat_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notation.
        /// </summary>
        public static string FieldFormat_Notation {
            get {
                return ResourceManager.GetString("FieldFormat_Notation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apostrophe (&apos;).
        /// </summary>
        public static string FormatSetting_Apostrophe {
            get {
                return ResourceManager.GetString("FormatSetting_Apostrophe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon (:).
        /// </summary>
        public static string FormatSetting_Colon {
            get {
                return ResourceManager.GetString("FormatSetting_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma (,).
        /// </summary>
        public static string FormatSetting_Comma {
            get {
                return ResourceManager.GetString("FormatSetting_Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphen (-).
        /// </summary>
        public static string FormatSetting_Dash {
            get {
                return ResourceManager.GetString("FormatSetting_Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full stop (.).
        /// </summary>
        public static string FormatSetting_FullStop {
            get {
                return ResourceManager.GetString("FormatSetting_FullStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string FormatSetting_None {
            get {
                return ResourceManager.GetString("FormatSetting_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slash (/).
        /// </summary>
        public static string FormatSetting_Slash {
            get {
                return ResourceManager.GetString("FormatSetting_Slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space ( ).
        /// </summary>
        public static string FormatSetting_Space {
            get {
                return ResourceManager.GetString("FormatSetting_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request. Please contact your system &lt;a class=&quot;mailto&quot; href=&quot;mailto:servicedesk@everyangle.com&quot; target=&quot;_top&quot;&gt;administrator&lt;/a&gt;..
        /// </summary>
        public static string Generic_Error_Message {
            get {
                return ResourceManager.GetString("Generic_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create chart.
        /// </summary>
        public static string Label_ActionDropdown_CreateChart {
            get {
                return ResourceManager.GetString("Label_ActionDropdown_CreateChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create list.
        /// </summary>
        public static string Label_ActionDropdown_CreateList {
            get {
                return ResourceManager.GetString("Label_ActionDropdown_CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create pivot.
        /// </summary>
        public static string Label_ActionDropdown_CreatePivot {
            get {
                return ResourceManager.GetString("Label_ActionDropdown_CreatePivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Dashboard.
        /// </summary>
        public static string Label_ActionDropdown_ExecuteDashboard {
            get {
                return ResourceManager.GetString("Label_ActionDropdown_ExecuteDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Display.
        /// </summary>
        public static string Label_ActionDropdown_ExecuteDisplay {
            get {
                return ResourceManager.GetString("Label_ActionDropdown_ExecuteDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle description.
        /// </summary>
        public static string Label_AdvanceFilter_AngleDescription {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_AngleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string Label_AdvanceFilter_AngleDisplayName {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_AngleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle ID.
        /// </summary>
        public static string Label_AdvanceFilter_AngleId {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_AngleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle name.
        /// </summary>
        public static string Label_AdvanceFilter_AngleName {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_AngleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start object.
        /// </summary>
        public static string Label_AdvanceFilter_BaseClasses {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_BaseClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display description.
        /// </summary>
        public static string Label_AdvanceFilter_DisplayDescription {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_DisplayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        public static string Label_AdvanceFilter_Followup {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_Followup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last changed by.
        /// </summary>
        public static string Label_AdvanceFilter_LastChangedBy {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_LastChangedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication status.
        /// </summary>
        public static string Label_AdvanceFilter_PulicationStatus {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_PulicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Label_AdvanceFilter_QueryStep {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_QueryStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Jump.
        /// </summary>
        public static string Label_AdvanceFilter_Search_AllowFollowup {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_Search_AllowFollowup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow more detail.
        /// </summary>
        public static string Label_AdvanceFilter_Search_AllowMoreDetail {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_Search_AllowMoreDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search label.
        /// </summary>
        public static string Label_AdvanceFilter_Search_Label {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_Search_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege label.
        /// </summary>
        public static string Label_AdvanceFilter_Search_Private_Label {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_Search_Private_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starred status.
        /// </summary>
        public static string Label_AdvanceFilter_StarredStatus {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_StarredStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation status.
        /// </summary>
        public static string Label_AdvanceFilter_ValidationStatus {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_ValidationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning status.
        /// </summary>
        public static string Label_AdvanceFilter_WarningStatus {
            get {
                return ResourceManager.GetString("Label_AdvanceFilter_WarningStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed with model role.
        /// </summary>
        public static string Label_Angle_ExecuteWithModelRole {
            get {
                return ResourceManager.GetString("Label_Angle_ExecuteWithModelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add definitions sheet.
        /// </summary>
        public static string Label_Angle_Export_AddDefinitionSheet {
            get {
                return ResourceManager.GetString("Label_Angle_Export_AddDefinitionSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add summary sheet.
        /// </summary>
        public static string Label_Angle_Export_AddSummarySheet {
            get {
                return ResourceManager.GetString("Label_Angle_Export_AddSummarySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string Label_Angle_Export_FileName {
            get {
                return ResourceManager.GetString("Label_Angle_Export_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header format.
        /// </summary>
        public static string Label_Angle_Export_HeaderFormat {
            get {
                return ResourceManager.GetString("Label_Angle_Export_HeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items.
        /// </summary>
        public static string Label_Angle_Export_NumberOfItems {
            get {
                return ResourceManager.GetString("Label_Angle_Export_NumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet name.
        /// </summary>
        public static string Label_Angle_Export_SheetName {
            get {
                return ResourceManager.GetString("Label_Angle_Export_SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in aggregated format.
        /// </summary>
        public static string Label_Angle_Export_ShowInAggregatedFormat {
            get {
                return ResourceManager.GetString("Label_Angle_Export_ShowInAggregatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System location.
        /// </summary>
        public static string Label_Angle_Privilleges_SystemLocation {
            get {
                return ResourceManager.GetString("Label_Angle_Privilleges_SystemLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package ID.
        /// </summary>
        public static string Label_AngleExport_PackageId {
            get {
                return ResourceManager.GetString("Label_AngleExport_PackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis scale.
        /// </summary>
        public static string Label_ChartOptions_AxisScale {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Label_ChartOptions_AxisScale_Automatic {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisScale_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Label_ChartOptions_AxisScale_Manual {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisScale_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis titles.
        /// </summary>
        public static string Label_ChartOptions_AxisTitle {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide axis titles.
        /// </summary>
        public static string Label_ChartOptions_AxisTitle_Hide {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisTitle_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show axis titles.
        /// </summary>
        public static string Label_ChartOptions_AxisTitle_Show {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisTitle_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show X-axis title.
        /// </summary>
        public static string Label_ChartOptions_AxisTitle_ShowX {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisTitle_ShowX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Y-axis title.
        /// </summary>
        public static string Label_ChartOptions_AxisTitle_ShowY {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisTitle_ShowY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis values.
        /// </summary>
        public static string Label_ChartOptions_AxisValue {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide axis values.
        /// </summary>
        public static string Label_ChartOptions_AxisValue_Hide {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisValue_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show axis values.
        /// </summary>
        public static string Label_ChartOptions_AxisValue_Show {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisValue_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show X-axis values.
        /// </summary>
        public static string Label_ChartOptions_AxisValue_ShowX {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisValue_ShowX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Y-axis values.
        /// </summary>
        public static string Label_ChartOptions_AxisValue_ShowY {
            get {
                return ResourceManager.GetString("Label_ChartOptions_AxisValue_ShowY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data labels.
        /// </summary>
        public static string Label_ChartOptions_DataLabel {
            get {
                return ResourceManager.GetString("Label_ChartOptions_DataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide data labels.
        /// </summary>
        public static string Label_ChartOptions_DataLabel_Hide {
            get {
                return ResourceManager.GetString("Label_ChartOptions_DataLabel_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover.
        /// </summary>
        public static string Label_ChartOptions_DataLabel_Mouse {
            get {
                return ResourceManager.GetString("Label_ChartOptions_DataLabel_Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show data labels.
        /// </summary>
        public static string Label_ChartOptions_DataLabel_Show {
            get {
                return ResourceManager.GetString("Label_ChartOptions_DataLabel_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show values only.
        /// </summary>
        public static string Label_ChartOptions_DataLabel_ShowValues {
            get {
                return ResourceManager.GetString("Label_ChartOptions_DataLabel_ShowValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gridlines.
        /// </summary>
        public static string Label_ChartOptions_Gridline {
            get {
                return ResourceManager.GetString("Label_ChartOptions_Gridline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Label_ChartOptions_Gridline_Hide {
            get {
                return ResourceManager.GetString("Label_ChartOptions_Gridline_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string Label_ChartOptions_Gridline_Show {
            get {
                return ResourceManager.GetString("Label_ChartOptions_Gridline_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string Label_ChartOptions_Gridline_ShowX {
            get {
                return ResourceManager.GetString("Label_ChartOptions_Gridline_ShowX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string Label_ChartOptions_Gridline_ShowY {
            get {
                return ResourceManager.GetString("Label_ChartOptions_Gridline_ShowY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide gridlines.
        /// </summary>
        public static string Label_ChartOptions_GridlineRadar_Hide {
            get {
                return ResourceManager.GetString("Label_ChartOptions_GridlineRadar_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show gridlines.
        /// </summary>
        public static string Label_ChartOptions_GridlineRadar_Show {
            get {
                return ResourceManager.GetString("Label_ChartOptions_GridlineRadar_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gridline type.
        /// </summary>
        public static string Label_ChartOptions_GridlineType {
            get {
                return ResourceManager.GetString("Label_ChartOptions_GridlineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc.
        /// </summary>
        public static string Label_ChartOptions_GridlineType_Arc {
            get {
                return ResourceManager.GetString("Label_ChartOptions_GridlineType_Arc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Label_ChartOptions_GridlineType_Line {
            get {
                return ResourceManager.GetString("Label_ChartOptions_GridlineType_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Label_ChartOptions_Legend {
            get {
                return ResourceManager.GetString("Label_ChartOptions_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide legend.
        /// </summary>
        public static string Label_ChartOptions_Legend_Hide {
            get {
                return ResourceManager.GetString("Label_ChartOptions_Legend_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show legend.
        /// </summary>
        public static string Label_ChartOptions_Legend_Show {
            get {
                return ResourceManager.GetString("Label_ChartOptions_Legend_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranges.
        /// </summary>
        public static string Label_ChartOptions_Ranges {
            get {
                return ResourceManager.GetString("Label_ChartOptions_Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide ranges.
        /// </summary>
        public static string Label_ChartOptions_Ranges_Hide {
            get {
                return ResourceManager.GetString("Label_ChartOptions_Ranges_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ranges.
        /// </summary>
        public static string Label_ChartOptions_Ranges_Show {
            get {
                return ResourceManager.GetString("Label_ChartOptions_Ranges_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show as Percentage.
        /// </summary>
        public static string Label_ChartOptions_ShowAsPercentage {
            get {
                return ResourceManager.GetString("Label_ChartOptions_ShowAsPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert model date.
        /// </summary>
        public static string Label_CSV_Export_AddModelDate {
            get {
                return ResourceManager.GetString("Label_CSV_Export_AddModelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No character.
        /// </summary>
        public static string Label_CSV_Export_BoolChars {
            get {
                return ResourceManager.GetString("Label_CSV_Export_BoolChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format.
        /// </summary>
        public static string Label_CSV_Export_DateFormat {
            get {
                return ResourceManager.GetString("Label_CSV_Export_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date separator.
        /// </summary>
        public static string Label_CSV_Export_DateSeparator {
            get {
                return ResourceManager.GetString("Label_CSV_Export_DateSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimals.
        /// </summary>
        public static string Label_CSV_Export_Decimal {
            get {
                return ResourceManager.GetString("Label_CSV_Export_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal separator.
        /// </summary>
        public static string Label_CSV_Export_DecimalSeparator {
            get {
                return ResourceManager.GetString("Label_CSV_Export_DecimalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use text qualifier.
        /// </summary>
        public static string Label_CSV_Export_Enquote {
            get {
                return ResourceManager.GetString("Label_CSV_Export_Enquote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text qualifier.
        /// </summary>
        public static string Label_CSV_Export_EnquoteCharacter {
            get {
                return ResourceManager.GetString("Label_CSV_Export_EnquoteCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use text qualifier on headers.
        /// </summary>
        public static string Label_CSV_Export_EnquoteHeaders {
            get {
                return ResourceManager.GetString("Label_CSV_Export_EnquoteHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set format.
        /// </summary>
        public static string Label_CSV_Export_EnumFormat {
            get {
                return ResourceManager.GetString("Label_CSV_Export_EnumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field delimiter.
        /// </summary>
        public static string Label_CSV_Export_FieldSeparator {
            get {
                return ResourceManager.GetString("Label_CSV_Export_FieldSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header rows.
        /// </summary>
        public static string Label_CSV_Export_HeaderRows {
            get {
                return ResourceManager.GetString("Label_CSV_Export_HeaderRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line delimiter.
        /// </summary>
        public static string Label_CSV_Export_LineSeparator {
            get {
                return ResourceManager.GetString("Label_CSV_Export_LineSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Label_CSV_Export_ModelDate_None {
            get {
                return ResourceManager.GetString("Label_CSV_Export_ModelDate_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select column.
        /// </summary>
        public static string Label_CSV_Export_ModelDate_Placeholder {
            get {
                return ResourceManager.GetString("Label_CSV_Export_ModelDate_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File options.
        /// </summary>
        public static string Label_CSV_Export_SectionFileOptions {
            get {
                return ResourceManager.GetString("Label_CSV_Export_SectionFileOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format options.
        /// </summary>
        public static string Label_CSV_Export_SectionFormatOptions {
            get {
                return ResourceManager.GetString("Label_CSV_Export_SectionFormatOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time format.
        /// </summary>
        public static string Label_CSV_Export_TimeFormat {
            get {
                return ResourceManager.GetString("Label_CSV_Export_TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time separator.
        /// </summary>
        public static string Label_CSV_Export_TimeSeparator {
            get {
                return ResourceManager.GetString("Label_CSV_Export_TimeSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to new Dashboard.
        /// </summary>
        public static string Label_Dashboard_AddToANewDashboard {
            get {
                return ResourceManager.GetString("Label_Dashboard_AddToANewDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to existing Dashboard.
        /// </summary>
        public static string Label_Dashboard_AddToExistingDashboard {
            get {
                return ResourceManager.GetString("Label_Dashboard_AddToExistingDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed with model role.
        /// </summary>
        public static string Label_Dashboard_ExecuteWithModelRole {
            get {
                return ResourceManager.GetString("Label_Dashboard_ExecuteWithModelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Displays on Dashboard.
        /// </summary>
        public static string Label_Dashboard_NumberOfDisplays {
            get {
                return ResourceManager.GetString("Label_Dashboard_NumberOfDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Displays.
        /// </summary>
        public static string Label_Dashboard_PrivateDisplays {
            get {
                return ResourceManager.GetString("Label_Dashboard_PrivateDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Displays.
        /// </summary>
        public static string Label_Dashboard_PublicDisplays {
            get {
                return ResourceManager.GetString("Label_Dashboard_PublicDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel report.
        /// </summary>
        public static string Label_Excel_Report {
            get {
                return ResourceManager.GetString("Label_Excel_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Label_FieldFormat_Date {
            get {
                return ResourceManager.GetString("Label_FieldFormat_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Label_FieldFormat_Day {
            get {
                return ResourceManager.GetString("Label_FieldFormat_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal separator.
        /// </summary>
        public static string Label_FieldFormat_DecimalSeparate {
            get {
                return ResourceManager.GetString("Label_FieldFormat_DecimalSeparate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Label_FieldFormat_Hour {
            get {
                return ResourceManager.GetString("Label_FieldFormat_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Label_FieldFormat_Hours {
            get {
                return ResourceManager.GetString("Label_FieldFormat_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Label_FieldFormat_Minutes {
            get {
                return ResourceManager.GetString("Label_FieldFormat_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Label_FieldFormat_Month {
            get {
                return ResourceManager.GetString("Label_FieldFormat_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string Label_FieldFormat_Numbers {
            get {
                return ResourceManager.GetString("Label_FieldFormat_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Label_FieldFormat_Order {
            get {
                return ResourceManager.GetString("Label_FieldFormat_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Label_FieldFormat_Other {
            get {
                return ResourceManager.GetString("Label_FieldFormat_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Label_FieldFormat_Seconds {
            get {
                return ResourceManager.GetString("Label_FieldFormat_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter.
        /// </summary>
        public static string Label_FieldFormat_Separator {
            get {
                return ResourceManager.GetString("Label_FieldFormat_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousands separator.
        /// </summary>
        public static string Label_FieldFormat_ThousandSeperator {
            get {
                return ResourceManager.GetString("Label_FieldFormat_ThousandSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use thousands separator.
        /// </summary>
        public static string Label_FieldFormat_UseThousandSeperator {
            get {
                return ResourceManager.GetString("Label_FieldFormat_UseThousandSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Label_FieldFormat_Year {
            get {
                return ResourceManager.GetString("Label_FieldFormat_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items available for automatic execution..
        /// </summary>
        public static string Label_No_Information_About_AutoExecute {
            get {
                return ResourceManager.GetString("Label_No_Information_About_AutoExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training movies.
        /// </summary>
        public static string Label_Search_WelcomeMovieTitle {
            get {
                return ResourceManager.GetString("Label_Search_WelcomeMovieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Label_Sort_Ascending {
            get {
                return ResourceManager.GetString("Label_Sort_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string Label_Sort_By {
            get {
                return ResourceManager.GetString("Label_Sort_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Label_Sort_Descending {
            get {
                return ResourceManager.GetString("Label_Sort_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then by:.
        /// </summary>
        public static string Label_Sort_ThenBy {
            get {
                return ResourceManager.GetString("Label_Sort_ThenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsorted.
        /// </summary>
        public static string Label_Unsorted {
            get {
                return ResourceManager.GetString("Label_Unsorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Process labels.
        /// </summary>
        public static string MassChange_BP_Tab_Title {
            get {
                return ResourceManager.GetString("MassChange_BP_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string MassChange_Category_Title {
            get {
                return ResourceManager.GetString("MassChange_Category_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave unchanged.
        /// </summary>
        public static string MassChange_Label_LeaveUnchanged {
            get {
                return ResourceManager.GetString("MassChange_Label_LeaveUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: To add/remove labels, only select Angle(s) from the same model..
        /// </summary>
        public static string MassChange_Label_NoModelSelected {
            get {
                return ResourceManager.GetString("MassChange_Label_NoModelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items:.
        /// </summary>
        public static string MassChange_Label_NumberItems {
            get {
                return ResourceManager.GetString("MassChange_Label_NumberItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to &quot;Angle&quot;.
        /// </summary>
        public static string MassChange_Label_SetToNormalAngle {
            get {
                return ResourceManager.GetString("MassChange_Label_SetToNormalAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to &quot;Not starred&quot;.
        /// </summary>
        public static string MassChange_Label_SetToNotStarred {
            get {
                return ResourceManager.GetString("MassChange_Label_SetToNotStarred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to &quot;Not validated&quot;.
        /// </summary>
        public static string MassChange_Label_SetToNotValidated {
            get {
                return ResourceManager.GetString("MassChange_Label_SetToNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to &quot;Private&quot;.
        /// </summary>
        public static string MassChange_Label_SetToPrivate {
            get {
                return ResourceManager.GetString("MassChange_Label_SetToPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to &quot;Published&quot;.
        /// </summary>
        public static string MassChange_Label_SetToPublished {
            get {
                return ResourceManager.GetString("MassChange_Label_SetToPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to &quot;Starred&quot;.
        /// </summary>
        public static string MassChange_Label_SetToStarred {
            get {
                return ResourceManager.GetString("MassChange_Label_SetToStarred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to &quot;Template&quot;.
        /// </summary>
        public static string MassChange_Label_SetToTemplate {
            get {
                return ResourceManager.GetString("MassChange_Label_SetToTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to &quot;Validated&quot;.
        /// </summary>
        public static string MassChange_Label_SetToValidated {
            get {
                return ResourceManager.GetString("MassChange_Label_SetToValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update note.
        /// </summary>
        public static string MassChange_Label_Updatenote {
            get {
                return ResourceManager.GetString("MassChange_Label_Updatenote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege labels.
        /// </summary>
        public static string MassChange_PrivilegeLabel_Tab_Title {
            get {
                return ResourceManager.GetString("MassChange_PrivilegeLabel_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string MassChange_ReportHeader_Failed {
            get {
                return ResourceManager.GetString("MassChange_ReportHeader_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string MassChange_ReportHeader_Successful {
            get {
                return ResourceManager.GetString("MassChange_ReportHeader_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search labels.
        /// </summary>
        public static string MassChange_SearchLabel_Tab_Title {
            get {
                return ResourceManager.GetString("MassChange_SearchLabel_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors and warnings.
        /// </summary>
        public static string MC_Button_OpenErrorWarningLog {
            get {
                return ResourceManager.GetString("MC_Button_OpenErrorWarningLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System log.
        /// </summary>
        public static string MC_GlobalSetting_SystemLog_Title {
            get {
                return ResourceManager.GetString("MC_GlobalSetting_SystemLog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle automation.
        /// </summary>
        public static string MC_Label_AngleAutomation {
            get {
                return ResourceManager.GetString("MC_Label_AngleAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETL Designer.
        /// </summary>
        public static string MC_Label_ETLDesigner {
            get {
                return ResourceManager.GetString("MC_Label_ETLDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OData service.
        /// </summary>
        public static string MC_Label_ODataService {
            get {
                return ResourceManager.GetString("MC_Label_ODataService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail task if this action fails.
        /// </summary>
        public static string MC_Label_ScriptAbortTaskWhenError {
            get {
                return ResourceManager.GetString("MC_Label_ScriptAbortTaskWhenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program/script.
        /// </summary>
        public static string MC_Label_ScriptName {
            get {
                return ResourceManager.GetString("MC_Label_ScriptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add arguments&lt;br /&gt;(optional).
        /// </summary>
        public static string MC_Label_ScriptParameters {
            get {
                return ResourceManager.GetString("MC_Label_ScriptParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and retry.
        /// </summary>
        public static string MC_SAP_Jobs_Cancel_And_Retry {
            get {
                return ResourceManager.GetString("MC_SAP_Jobs_Cancel_And_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extractor status.
        /// </summary>
        public static string MC_SAP_Jobs_Extractor_Status {
            get {
                return ResourceManager.GetString("MC_SAP_Jobs_Extractor_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Angle - Angle page.
        /// </summary>
        public static string Page_Angle_Title {
            get {
                return ResourceManager.GetString("Page_Angle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Angle - Dashboard.
        /// </summary>
        public static string Page_Dashboard_Title {
            get {
                return ResourceManager.GetString("Page_Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Angle - Search page.
        /// </summary>
        public static string Page_Search_Title {
            get {
                return ResourceManager.GetString("Page_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show totals.
        /// </summary>
        public static string Pivot_Option_DoNotShowTotals {
            get {
                return ResourceManager.GetString("Pivot_Option_DoNotShowTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subtotals.
        /// </summary>
        public static string Pivot_Option_IncludeSubtotals {
            get {
                return ResourceManager.GetString("Pivot_Option_IncludeSubtotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentages.
        /// </summary>
        public static string Pivot_Option_Percentages {
            get {
                return ResourceManager.GetString("Pivot_Option_Percentages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show for columns.
        /// </summary>
        public static string Pivot_Option_ShowForColumns {
            get {
                return ResourceManager.GetString("Pivot_Option_ShowForColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show for rows.
        /// </summary>
        public static string Pivot_Option_ShowForRows {
            get {
                return ResourceManager.GetString("Pivot_Option_ShowForRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show for rows and columns.
        /// </summary>
        public static string Pivot_Option_ShowForRowsAndColumns {
            get {
                return ResourceManager.GetString("Pivot_Option_ShowForRowsAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        public static string Pivot_Option_Totals {
            get {
                return ResourceManager.GetString("Pivot_Option_Totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom/right.
        /// </summary>
        public static string Pivot_Option_TotalsLocation_Far {
            get {
                return ResourceManager.GetString("Pivot_Option_TotalsLocation_Far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top/left.
        /// </summary>
        public static string Pivot_Option_TotalsLocation_Near {
            get {
                return ResourceManager.GetString("Pivot_Option_TotalsLocation_Near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of column {0}.
        /// </summary>
        public static string Pivot_PercentOfColumn {
            get {
                return ResourceManager.GetString("Pivot_PercentOfColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of row {0}.
        /// </summary>
        public static string Pivot_PercentOfRow {
            get {
                return ResourceManager.GetString("Pivot_PercentOfRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of total {0}.
        /// </summary>
        public static string Pivot_PercentOfTotal {
            get {
                return ResourceManager.GetString("Pivot_PercentOfTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show totals for.
        /// </summary>
        public static string Pivot_Show_Total_For {
            get {
                return ResourceManager.GetString("Pivot_Show_Total_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Pivot_Total_For_Column {
            get {
                return ResourceManager.GetString("Pivot_Total_For_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Pivot_Total_For_None {
            get {
                return ResourceManager.GetString("Pivot_Total_For_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Pivot_Total_For_Row {
            get {
                return ResourceManager.GetString("Pivot_Total_For_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row and column.
        /// </summary>
        public static string Pivot_Total_For_RowAndColumn {
            get {
                return ResourceManager.GetString("Pivot_Total_For_RowAndColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort {0} by this column.
        /// </summary>
        public static string PivotCustomSort_LabelColumn {
            get {
                return ResourceManager.GetString("PivotCustomSort_LabelColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort {0} by this row.
        /// </summary>
        public static string PivotCustomSort_LabelRow {
            get {
                return ResourceManager.GetString("PivotCustomSort_LabelRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Information.
        /// </summary>
        public static string Popup_Angle_Info {
            get {
                return ResourceManager.GetString("Popup_Angle_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Angle for {0}.
        /// </summary>
        public static string Popup_CreateNewAngle_DropdownText {
            get {
                return ResourceManager.GetString("Popup_CreateNewAngle_DropdownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Angle for model {0}: {1}.
        /// </summary>
        public static string Popup_CreateNewAngle_TitleByType {
            get {
                return ResourceManager.GetString("Popup_CreateNewAngle_TitleByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Angle for model {0}.
        /// </summary>
        public static string Popup_CreateNewAngle_TitleOptions {
            get {
                return ResourceManager.GetString("Popup_CreateNewAngle_TitleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Information.
        /// </summary>
        public static string Popup_Dashboard_Info {
            get {
                return ResourceManager.GetString("Popup_Dashboard_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Information.
        /// </summary>
        public static string Popup_Display_Info {
            get {
                return ResourceManager.GetString("Popup_Display_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Jump to apply.
        /// </summary>
        public static string Popup_Followup_Title {
            get {
                return ResourceManager.GetString("Popup_Followup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object info.
        /// </summary>
        public static string Popup_HelpText_TitleClass {
            get {
                return ResourceManager.GetString("Popup_HelpText_TitleClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field info.
        /// </summary>
        public static string Popup_HelpText_TitleField {
            get {
                return ResourceManager.GetString("Popup_HelpText_TitleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump info.
        /// </summary>
        public static string Popup_HelpText_TitleFollowup {
            get {
                return ResourceManager.GetString("Popup_HelpText_TitleFollowup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for model:.
        /// </summary>
        public static string Popup_ModelParameters_Label_Model {
            get {
                return ResourceManager.GetString("Popup_ModelParameters_Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model parameters.
        /// </summary>
        public static string Popup_ModelParameters_Title {
            get {
                return ResourceManager.GetString("Popup_ModelParameters_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Popup_ResultSummary_Title {
            get {
                return ResourceManager.GetString("Popup_ResultSummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        public static string Popup_SaveAsCSV_Title {
            get {
                return ResourceManager.GetString("Popup_SaveAsCSV_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task owner.
        /// </summary>
        public static string ResolveAngleDisplay_TaskCreator {
            get {
                return ResourceManager.GetString("ResolveAngleDisplay_TaskCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action datastore.
        /// </summary>
        public static string ResolveAngleDisplay_TaskDatastore {
            get {
                return ResourceManager.GetString("ResolveAngleDisplay_TaskDatastore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string ResolveAngleDisplay_TaskName {
            get {
                return ResourceManager.GetString("ResolveAngleDisplay_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete task.
        /// </summary>
        public static string ResolveAngleDisplay_WillDeleteTask {
            get {
                return ResourceManager.GetString("ResolveAngleDisplay_WillDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No character.
        /// </summary>
        public static string SaveAsCSV_BoolChars_False {
            get {
                return ResourceManager.GetString("SaveAsCSV_BoolChars_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes character.
        /// </summary>
        public static string SaveAsCSV_BoolChars_True {
            get {
                return ResourceManager.GetString("SaveAsCSV_BoolChars_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string SaveAsCSV_FileName {
            get {
                return ResourceManager.GetString("SaveAsCSV_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart options.
        /// </summary>
        public static string Title_AggregationChart {
            get {
                return ResourceManager.GetString("Title_AggregationChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivot options.
        /// </summary>
        public static string Title_AggregationPivot {
            get {
                return ResourceManager.GetString("Title_AggregationPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Title_ChartOptions {
            get {
                return ResourceManager.GetString("Title_ChartOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to deselect.
        /// </summary>
        public static string Tooltip_BusinessProcess_Deselect {
            get {
                return ResourceManager.GetString("Tooltip_BusinessProcess_Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select.
        /// </summary>
        public static string Tooltip_BusinessProcess_Select {
            get {
                return ResourceManager.GetString("Tooltip_BusinessProcess_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request could not be executed due to semantic errors..
        /// </summary>
        public static string UnProcessEntity_Header_Message {
            get {
                return ResourceManager.GetString("UnProcessEntity_Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string WidgetFilter_ArgumentAdvance {
            get {
                return ResourceManager.GetString("WidgetFilter_ArgumentAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string WidgetFilter_ArgumentPeriod_Last {
            get {
                return ResourceManager.GetString("WidgetFilter_ArgumentPeriod_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string WidgetFilter_ArgumentPeriod_Next {
            get {
                return ResourceManager.GetString("WidgetFilter_ArgumentPeriod_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This.
        /// </summary>
        public static string WidgetFilter_ArgumentPeriod_This {
            get {
                return ResourceManager.GetString("WidgetFilter_ArgumentPeriod_This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string WidgetFilter_ArgumentType_Field {
            get {
                return ResourceManager.GetString("WidgetFilter_ArgumentType_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string WidgetFilter_ArgumentType_Function {
            get {
                return ResourceManager.GetString("WidgetFilter_ArgumentType_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string WidgetFilter_ArgumentType_Value {
            get {
                return ResourceManager.GetString("WidgetFilter_ArgumentType_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day(s).
        /// </summary>
        public static string WidgetFilter_PeriodType_Days {
            get {
                return ResourceManager.GetString("WidgetFilter_PeriodType_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month(s).
        /// </summary>
        public static string WidgetFilter_PeriodType_Months {
            get {
                return ResourceManager.GetString("WidgetFilter_PeriodType_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter(s).
        /// </summary>
        public static string WidgetFilter_PeriodType_Quarters {
            get {
                return ResourceManager.GetString("WidgetFilter_PeriodType_Quarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester(s).
        /// </summary>
        public static string WidgetFilter_PeriodType_Semesters {
            get {
                return ResourceManager.GetString("WidgetFilter_PeriodType_Semesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimester(s).
        /// </summary>
        public static string WidgetFilter_PeriodType_Trimesters {
            get {
                return ResourceManager.GetString("WidgetFilter_PeriodType_Trimesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week(s).
        /// </summary>
        public static string WidgetFilter_PeriodType_Weeks {
            get {
                return ResourceManager.GetString("WidgetFilter_PeriodType_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year(s).
        /// </summary>
        public static string WidgetFilter_PeriodType_Years {
            get {
                return ResourceManager.GetString("WidgetFilter_PeriodType_Years", resourceCulture);
            }
        }
    }
}
