var executeParameterHtmlTemplate = function () {
    return [
        '<div class="card">',
            '<ul class="accordion accrodion-bg-white">',
                '<li class="accordion-item">',
                    '<div class="accordion-header open" id="ExecutionParametersAngleAccordion">',
                        '<i class="open-indicator icon icon-chevron-down"></i>',
                        '<i class="close-indicator icon icon-chevron-right"></i>',
                        '<div class="displayNameContainer small">',
                            '<div class="front col-angle-icon">',
                            '</div>',
                            '<div class="col-angle-name"></div>',
                        '</div>',
                        '<div class="angelStartObject">',
                            '<div class="startObjectText">',
                                Localization.StartObject,
                            '</div>',
                            '<div class="col-angle-object"></div>',
                        '</div>',
                    '</div>',
                    '<div class="accordion-body">',
                        '<div class="card-body section-angle">',
                            '<div class="form-row row-title"></div>',
                            '<div class="form-row">',
                                '<div class="form-col form-col-body"><hr/></div>',
                            '</div>',
                            '<div class="form-row row-definition">',
                                '<div class="form-col form-col-body col-definition col-angle-definition"></div>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</li>',
                '<li class="accordion-item">',
                    '<div class="accordion-header open" id="ExecutionParametersDispalyAccordion">',
                        '<i class="open-indicator icon icon-chevron-down"></i>',
                        '<i class="close-indicator icon icon-chevron-right"></i>',
                        '<div class="displayNameContainer small">',
                            '<div class="front col-display-icon">',
                        '</div>',
                            '<div class="col-display-name"></div>',
                        '</div>',
                    '</div>',
                    '<div class="accordion-body">',
                        '<div class="card-body section-display">',
                            '<div class="form-row row-title"></div>',
                            '<div class="form-row">',
                                '<div class="form-col form-col-body"><hr/></div>',
                            '</div>',
                            '<div class="form-row row-definition">',
                                '<div class="form-col form-col-body col-definition col-display-definition"></div>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</li>',
            '</ul>',
        '</div>'
    ].join('');
};
