var executeParameterHtmlTemplate = function () {
    return [
        '<div class="card">',
            '<div class="card-body section-angle">',
                '<div class="form-row row-title">',
                    '<div class="form-col form-col-header">',
                        Localization.StartObject,
                    '</div>',
                    '<div class="form-col form-col-body col-angle-object"></div>',
                '</div>',
                '<div class="form-row">',
                    '<div class="form-col form-col-body"><hr/></div>',
                '</div>',
                '<div class="form-row row-definition">',
                    '<div class="form-col form-col-body col-definition col-angle-definition"></div>',
                '</div>',
            '</div>',
            '<div class="card-body section-display">',
                '<div class="form-row row-title">',
                    '<div class="form-col form-col-header">',
                        Localization.DisplayName,
                    '</div>',
                    '<div class="form-col form-col-body col-display-name"></div>',
                '</div>',
                '<div class="form-row">',
                    '<div class="form-col form-col-body"><hr/></div>',
                '</div>',
                '<div class="form-row row-definition">',
                    '<div class="form-col form-col-body col-definition col-display-definition"></div>',
                '</div>',
            '</div>',
        '</div>'
    ].join('');
};
