var massChangeHtmlTemplate = function () {
    return [
        '<div class="popupTabPanel" id="MassChangeArea">',
            '<div class="sectionGeneral">',
                '<h2>' + Localization.General + '</h2>',
                '<div class="row">',
                    '<div class="field">' + Localization.PersonalNote + '</div>',
                    '<div class="input">',
                        '<label>',
                            '<input id="AnglePrivateNoteCheckbox" type="checkbox" value="private_note" data-bind="checked: massChangeModel.IsChangePrivateNote" />',
                            '<span class="label"></span>',
                        '</label>',
                        '<input id="AnglePrivateNote" maxlength="100" type="text" value="" data-bind="value: massChangeModel.PrivateNote, enable: massChangeModel.IsChangePrivateNote" class="eaText eaTextSize40 txtPrivateNote" />',
                        '<span class="textStatus"></span>',
                    '</div>',
                '</div>',
            '</div>',
            '<div class="sectionStatus">',
                '<h2>' + Localization.Status + '</h2>',
                '<div class="row">',
                '<div class="field"><span>' + Localization.MassChangeStarred + '</span><img alt="" src="' + GetImageFolderPath() + 'searchpage/icn_starred_active.svg" height="20" width="20" /></div>',
                    '<div class="input">',
                        '<input id="IsStarred" type="checkbox" value="is_starred" data-bind="checked: massChangeModel.IsStarred, IndeterminatableChange: massChangeModel.IsStarred" />',
                        '<span class="textStatus"></span>',
                    '</div>',
                '</div>',
                '<div class="row" data-bind="visible: privilegesViewModel.IsAllowCreateAngle()">',
                '<div class="field"><span data-bind="text: Localization.MassChangePublished">' + Localization.MassChangePublished + '</span><img alt="" src="' + GetImageFolderPath() + 'searchpage/icn_public.svg" height="20" width="20" /></div>',
                    '<div class="input">',
                        '<input id="AngleIsPublished" type="checkbox" value="is_published" data-bind="checked: massChangeModel.IsPublished, IndeterminatableChange: massChangeModel.IsPublished" />',
                        '<span class="textStatus"></span>',
                    '</div>',
                '</div>',
                '<div class="row" data-bind="visible: privilegesViewModel.IsAllowCreateAngle()">',
                '<div class="field"><span>' + Localization.MassChangeValidated + '</span><img alt="" src="' + GetImageFolderPath() + 'searchpage/icn_validated.svg" height="20" width="20" /></div>',
                    '<div class="input">',
                        '<input id="AngleIsValidate" type="checkbox" value="is_validated" data-bind="checked: massChangeModel.IsValidated, IndeterminatableChange: massChangeModel.IsValidated" />',
                        '<span class="textStatus"></span>',
                    '</div>',
                '</div>',
                '<div class="row" data-bind="visible: privilegesViewModel.IsAllowCreateAngle() && userModel.CanCreateTemplateAngle()">',
                '<div class="field"><span>' + Localization.MassChangeTemplate + '</span><img alt="" src="' + GetImageFolderPath() + 'searchpage/icn_item_angle.svg" height="20" width="20" /></div>',
                    '<div class="input">',
                        '<input id="AngleIsTemplate" type="checkbox" value="is_template" data-bind="checked: massChangeModel.IsTemplate, IndeterminatableChange: massChangeModel.IsTemplate" />',
                        '<span class="textStatus"></span>',
                    '</div>',
                '</div>',
            '</div>',
            '<div class="sectionLabels">',
                '<div class="tabMenuWrapper" id="LabelTabWrapper">',
                    '<ul class="tabMenu">',
                        '<li id="BPLabels" class="active" onclick="massChangeModel.LabelTabClick(enumHandlers.LABELVIEWTYPE.BP, this);" data-bind="css: { disabled: !massChangeModel.CanSetLabels() }"><span>' + Captions.MassChange_BP_Tab_Title + '</span></li>',
                        '<li id="SearchLabels" onclick="massChangeModel.LabelTabClick(enumHandlers.LABELVIEWTYPE.SEARCH, this);" data-bind="css: { disabled: !massChangeModel.CanSetLabels() }"><span>' + Captions.MassChange_SearchLabel_Tab_Title + '</span></li>',
                        '<li id="PrivilegeLabels" onclick="massChangeModel.LabelTabClick(enumHandlers.LABELVIEWTYPE.PRIVILEGE, this);" data-bind="css: { disabled: !massChangeModel.CanSetLabels() }"><span>' + Captions.MassChange_PrivilegeLabel_Tab_Title + '</span></li>',
                    '</ul>',
                '</div>',
                '<div id="Labels-PlaceHolder" data-bind="css: { disabled: !massChangeModel.CanSetLabels() }"></div>',
                '<div class="infoText">' + Captions.MassChange_Label_NoModelSelected + '</div>',
            '</div>',
        '</div>'
    ].join('');
};
