var anglePublishingHtmlTemplate = function () {
    var anglePublishingHtmlTemplate = "";
    anglePublishingHtmlTemplate += "<div class=\"popupTabPanel anglePublishingContainer\">";
    anglePublishingHtmlTemplate += "    <div class=\"sectionPublishing sectionPublishingDetails\">";
    anglePublishingHtmlTemplate += "        <div class=\"row\">";
    anglePublishingHtmlTemplate += "            <div class=\"field\">" + Localization.BusinessProcesses + "<\/div>";
    anglePublishingHtmlTemplate += "            <div class=\"input\" data-bind=\"text: bp_text, attr: { title: bp_text }\"><\/div>";
    anglePublishingHtmlTemplate += "        <\/div>";
    anglePublishingHtmlTemplate += "        <div class=\"row\">";
    anglePublishingHtmlTemplate += "            <div class=\"field\">" + Localization.Languages + "<\/div>";
    anglePublishingHtmlTemplate += "            <div class=\"input\" data-bind=\"text: language_text, attr: { title: language_text }\"><\/div>";
    anglePublishingHtmlTemplate += "        <\/div>";
    anglePublishingHtmlTemplate += "        <div class=\"row\">";
    anglePublishingHtmlTemplate += "            <div class=\"field\">" + Localization.PrivilegeLabels + "<\/div>";
    anglePublishingHtmlTemplate += "            <div class=\"input\" data-bind=\"text: privilege_label_text, attr: { title: privilege_label_text }\"><\/div>";
    anglePublishingHtmlTemplate += "        <\/div>";
    anglePublishingHtmlTemplate += "        <div class=\"row\">";
    anglePublishingHtmlTemplate += "            <div class=\"field\">" + Localization.SearchLabels + "<\/div>";
    anglePublishingHtmlTemplate += "            <div class=\"input\" data-bind=\"text: search_label_text, attr: { title: search_label_text }\"><\/div>";
    anglePublishingHtmlTemplate += "        <\/div>";
    anglePublishingHtmlTemplate += "    <\/div>";
    anglePublishingHtmlTemplate += "    <div class=\"StatSeparate\"><\/div>";
    anglePublishingHtmlTemplate += "";
    anglePublishingHtmlTemplate += "    <div class=\"sectionPublishing sectionPublishingDisplay\">";
    anglePublishingHtmlTemplate += "        <div class=\"row rowHeader\">";
    anglePublishingHtmlTemplate += "            <div class=\"field\">";
    anglePublishingHtmlTemplate += "                <span class=\"iconPrivate\"><\/span>";
    anglePublishingHtmlTemplate += "                <span class=\"iconPublic\"><\/span>";
    anglePublishingHtmlTemplate += "            <\/div>";
    anglePublishingHtmlTemplate += "            <div class=\"nonecursor\">" + Localization.DefaultDisplay + "<\/div>";
    anglePublishingHtmlTemplate += "        <\/div>";
    anglePublishingHtmlTemplate += "        <div class=\"rowContent\" data-bind=\"foreach: { data: display_definitions, as: 'display' }\">";
    anglePublishingHtmlTemplate += "            <div class=\"row\">";
    anglePublishingHtmlTemplate += "                <div class=\"field\">";
    anglePublishingHtmlTemplate += "                    <label>";
    anglePublishingHtmlTemplate += "                        <input type=\"radio\" value=\"private\" data-bind=\"attr: { name: 'chk-' + display.id }, checked: display.is_public_text\" \/>";
    anglePublishingHtmlTemplate += "                        <span class=\"label\"><\/span>";
    anglePublishingHtmlTemplate += "                    <\/label>";
    anglePublishingHtmlTemplate += "                    <label>";
    anglePublishingHtmlTemplate += "                        <input type=\"radio\" value=\"public\" data-bind=\"attr: { name: 'chk-' + display.id }, checked: display.is_public_text\" \/>";
    anglePublishingHtmlTemplate += "                        <span class=\"label\"><\/span>";
    anglePublishingHtmlTemplate += "                    <\/label>";
    anglePublishingHtmlTemplate += "                <\/div>";
    anglePublishingHtmlTemplate += "                <div class=\"input\" data-bind=\"css: { 'default' : display.id === $root.angle_default_display() }, html: '<span class=\\'icon ' + display.display_type + '\\'><\/span>' + display.name, click: function (model, event) { $root.angle_default_display(model.id); }\"><\/div>";
    anglePublishingHtmlTemplate += "            <\/div>";
    anglePublishingHtmlTemplate += "        <\/div>";
    anglePublishingHtmlTemplate += "    <\/div>";
    anglePublishingHtmlTemplate += "    <div class=\"publishingNote\" data-bind=\"html: Localization.MessagePublishingNote\">" + Localization.MessagePublishingNote + "<\/div>";
    anglePublishingHtmlTemplate += "<\/div>";

    return anglePublishingHtmlTemplate;
};
