var userSettingHtmlTemplate = function () {
    return [
        '<ul class="popupTabMenu" id="SettingTabs">',
            '<li id="UserDetailSetting"><a onclick="userSettingsView.UserSettingTabClick(userSettingsHandler.TAB.USERSETTING)">' + Localization.UserInformation + '</a></li>',
            '<li id="SystemSetting"><a onclick="userSettingsView.UserSettingTabClick(userSettingsHandler.TAB.SYSTEMSETTING)">' + Localization.SystemSettings + '</a></li>',
            '<li id="FormatSetting" class="hasSubMenu">',
                '<a onclick="userSettingsView.UserSettingTabClick(userSettingsHandler.TAB.FORMATSETTING)">' + Localization.FieldFormats + '</a>',
                '<ul class="subMenu">',
                    '<li id="FormatSettingGeneral" onclick="userSettingsView.UserSettingTabClick(userSettingsHandler.TAB.FORMATSETTINGGENERAL);"><a>' + Localization.FormatSettingLabelGeneral + '</a></li>',
                    '<li id="FormatSettingNumber" onclick="userSettingsView.UserSettingTabClick(userSettingsHandler.TAB.FORMATSETTINGNUMBER);"><a>' + Captions.Label_FieldFormat_Numbers + '</a></li>',
                    '<li id="FormatSettingCurrency" onclick="userSettingsView.UserSettingTabClick(userSettingsHandler.TAB.FORMATSETTINGCURRENCY);"><a>' + Localization.FormatSettingLabelCurrency + '</a></li>',
                    '<li id="FormatSettingPercentages" onclick="userSettingsView.UserSettingTabClick(userSettingsHandler.TAB.FORMATSETTINGPERCENTAGES);"><a>' + Localization.FormatSettingLabelPercentages + '</a></li>',
                    '<li id="FormatSettingDate" onclick="userSettingsView.UserSettingTabClick(userSettingsHandler.TAB.FORMATSETTINGDATE);"><a>' + Localization.FormatSettingLabelDate + '</a></li>',
                    '<li id="FormatSettingTime" onclick="userSettingsView.UserSettingTabClick(userSettingsHandler.TAB.FORMATSETTINGTIME);"><a>' + Localization.FormatSettingLabelTime + '</a></li>',
                    '<li id="FormatSettingSet" onclick="userSettingsView.UserSettingTabClick(userSettingsHandler.TAB.FORMATSETTINGSET);"><a>' + Localization.Enum + '</a></li>',
                '</ul>',
            '</li>',
            '<li id="ActionSetting" onclick="userSettingsView.UserSettingTabClick(userSettingsHandler.TAB.ACTIONSETTING);"><a>' + Localization.ActionsAtLogin + '</a></li>',
        '</ul>',
        '<div class="popupTabPanel" id="SettingArea">',
            '<div id="UserDetailSettingArea">',
                '<div id="UserInfomation">',
                    '<h2 id="UserInfoHeader">' + Localization.UserSettingLabelUserInfo + '</h2>',
                    '<div id="UserDetailTable">',
                        '<div class="row rowUsername">',
                            '<div class="field" id="UserInfoLabel">' + Localization.UserSettingLabelUser + '</div>',
                            '<div class="input" id="UserInfo"><span>' + userModel.FullnameWithId() + '</span></div>',
                        '</div>',
                        '<div class="row">',
                            '<div class="field" id="AssignRolesLabel">' + Localization.UserSettingLabelRoles + '</div>',
                            '<div class="input">',
                                '<div class="AssignRoles" id="AssignRoles" data-bind="foreach: userModel.GetAssignedRoles()">',
                                   '<span data-bind="text: $data.role_id, attr: { title: $data.model_id !== undefined ? $data.model_id + \' model role\' : \'System role\' }"></span><!-- ko if: $index() !== userModel.GetAssignedRoles().length - 1 -->, <!-- /ko -->',
                                '</div>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="sectionAuthorisations" id="AuthorisationModel">',
                    '<h2>' + Localization.UserSettingLabelAuthorisation + '</h2>',
                    '<div class="row">',
                        '<div class="field">' + Localization.Model + ':</div>',
                        '<div class="input"><input id="SystemModel" class="eaDropdown eaDropdownSize40" /></div>',
                    '</div>',
                    '<div id="AuthorizationStatus" data-bind="foreach: LabelAuthorisations">',
                        '<!-- ko if: $data.LabelCategories().length > 0 -->',
                        '<div class="row clearfix">',
                            '<div class="field labelGroup" data-bind="text: $data.StatusName"></div>',
                            '<div class="input labelCategories" data-bind="foreach: $data.LabelCategories">',
                                '<div class="row clearfix">',
                                    '<div class="field" data-bind="text: $data.CategoryName() ? $data.CategoryName : $data.CategoryId"></div>',
                                    '<div class="input labels" data-bind="foreach: $data.Labels">',
                                        '<span class="InfoFocus"><span data-bind="text: $data.LabelName() ? $data.LabelName : $data.LabelId"></span></span>',
                                    '</div>',
                                '</div>',
                            '</div>',
                        '</div>',
                        '<!-- /ko -->',
                    '</div>',
                '</div>',
            '</div>',
            '<div id="SystemSettingArea">',
                '<div class="row">',
                    '<div class="field" id="UserSettingsBusinessProcessesLabel">' + Localization.SystemSettingLabelDefaultBusinessProcess + '</div>',
                    '<div class="input inputBusinessProcesses">',
                        '<div id="UserSettingsBusinessProcesses"></div>',
                    '</div>',
                '</div>',
                '<div class="row rowLanguage">',
                    '<div class="columnLanguage">',
                        '<div class="field" id="LanguageTitle">' + Localization.AdvanceFilterLanguageTitle + '</div>',
                        '<div class="input" id="LanguageDropdownlist"><input id="LanguageSelect" class="eaDropdown eaDropdownSize40" /></div>',
                    '</div>',
                    '<div class="columnExportRow">',
                        '<div class="field" id="ExcelRowLabel" title="' + Localization.SystemSettingLabelDefaultOfRowsExportToExcel + '">' + Localization.SystemSettingLabelDefaultOfRowsExportToExcel + '</div>',
                        '<div class="input" id="ExcelRowSelectWrapper"><input id="ExcelRowSelect" class="eaDropdown eaDropdownSize40" /></div>',
                    '</div>',
                '</div>',
                '<div class="row rowFilter clearfix" data-bind="visible: userModel.IsPossibleToCreateAngle()">',
                    '<div class="field" id="GeneralFiltersLabel">' + Localization.GeneralFilters + '</div>',
                    '<div class="input">',
                        '<label>',
                            '<input id="ShowFacetAngleWarnings" type="checkbox" />',
                            '<span id="ShowFacetAngleWarningsLabel" class="label" data-bind="visible: userModel.IsPossibleToCreateAngle()">' + Localization.ShowFacetForAngleWarnings + '</span>',
                        '</label>',
                    '</div>',
                '</div>',
                '<div class="row rowFieldChooser clearfix">',
                    '<div class="field" id="DefaultFilterSuggestedStarredLabel">' + Localization.DefaultFilterSuggestedStarred + '</div>',
                    '<div class="input">',
                        '<div class="column">',
                            '<label>',
                                '<input id="DefaultStarredfields" type="checkbox" />',
                                '<span id="DefaultStarredfieldsLabel" class="label" >',
                                    '<img src="' + GetImageFolderPath() + 'searchpage/icn_starred_active.svg" alt="' + Localization.DefaultStarredfieldsLabel + '" height="20" width="20" />',
                                    '<span>' + Localization.DefaultStarredfieldsLabel + '</span>',
                                '</span>',
                            '</label>',
                        '</div>',
                    '</div>',
                    '<div class="input">',
                        '<div class="column">',
                            '<label>',
                                '<input id="DefaultSuggestedfields" type="checkbox" />',
                                '<span id="DefaultSuggestedfieldsLabel" class="label" >',
                                    '<img src="' + GetImageFolderPath() + 'searchpage/icn_suggest.png" alt="' + Localization.DefaultSuggestedfieldsLabel + '" height="20" width="20" />',
                                    '<span>' + Localization.DefaultSuggestedfieldsLabel + '</span>',
                                '</span>',
                            '</label>',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="row rowTechInfo clearfix">',
                    '<div class="field" id="ShowSAPPropertyNamesLabel">' + Localization.SystemSettingLabelShowSAPPropertyNames + '</div>',
                    '<div class="input">',
                        '<div class="column">',
                            '<label>',
                                '<input id="SapFieldsInChooser" type="checkbox" />',
                                '<span id="SapFieldsInChooserLabel" class="label">' + Localization.SystemSettingLabelWhenSelectingAProperty + '</span>',
                            '</label>',
                        '</div>',
                    '</div>',
                    '<div class="input">',
                        '<div class="column">',
                            '<label>',
                                '<input id="SapFieldsInHeader" type="checkbox" />',
                                '<span id="SapFieldsInHeaderLabel" class="label">' + Localization.SystemSettingLabelInColumnHeadersOfLists + '</span>',
                            '</label>',
                        '</div>',
                    '</div>',
                '</div>',
            '</div>',

            '<div id="FormatSettingGeneralArea" class="formatSettingsArea">',
                '<h2>' + Localization.FormatSettingLabelGeneral + '</h2>',
                '<fieldset>',
                    '<legend>' + Captions.FieldFormat_Example + '</legend>',
                    '<div class="formatExample">' + Captions.Label_FieldFormat_Numbers + ': <span class="exampleGeneralNumber"></span></div>',
                    '<div class="formatExample">' + Localization.FormatSettingLabelCurrency + ': <span class="exampleGeneralNumber"></span> EUR</div>',
                    '<div class="formatExample last">' + Localization.FormatSettingLabelPercentages + ': <span class="exampleGeneralNumber"></span> %</div>',
                '</fieldset>',
                '<div class="row clearfix">',
                    '<div class="field"><span>' + Captions.Label_FieldFormat_DecimalSeparate + '</span></div>',
                    '<div class="input"><input id="GeneralDecimalSeperatorDropdown" class="eaDropdown eaDropdownSize40" /></div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field" id=""><span>' + Captions.Label_FieldFormat_ThousandSeperator + '</span></div>',
                    '<div class="input"><input id="GeneralThousandSeperatorDropdown" class="eaDropdown eaDropdownSize40" /></div>',
                '</div>',
                '<div class="infoText formatDescription" id="generalExampleDescription"></div>',
            '</div>',

            '<div id="FormatSettingNumberArea" class="formatSettingsArea">',
                '<h2>' + Captions.Label_FieldFormat_Numbers + '</h2>',
                '<fieldset>',
                    '<legend>' + Captions.FieldFormat_Example + '</legend>',
                    '<div class="formatExample"><span class="exampleNumber"></span></div>',
                '</fieldset>',
                '<div class="row clearfix">',
                    '<div id="FormatDecimalLabel" class="field"><span>' + Localization.Decimal + '</span></div>',
                    '<div class="input" id="NumberDropdownlist"><input id="NumbersSelect" class="eaDropdown eaDropdownSize40" /></div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field" id="NumberFormatDisplayUnitLabel"><span>' + Localization.FormatSettingDisplayUnits + '</span></div>',
                    '<div class="input" id="NumberFormatDisplayUnitDropdownlist"><input id="NumberFormatDisplayUnitSelect" class="eaDropdown eaDropdownSize40" /></div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field"><span>' + Captions.Label_FieldFormat_UseThousandSeperator + '</span></div>',
                    '<div class="input">',
                        '<label>',
                            '<input type="checkbox" id="enable_thousandseparator_for_number" name="thousandseparator" value="number" onchange="userSettingsHandler.ChangeNumberFormat()">',
                            '<span class="label"></span>',
                        '</label>',
                    '</div>',
                '</div>',
                '<div class="infoText formatDescription" id="numberExampleDescription"></div>',
            '</div>',
             '<div id="FormatSettingCurrencyArea" class="formatSettingsArea">',
                '<h2>' + Localization.FormatSettingLabelCurrency + '</h2>',
                '<fieldset>',
                    '<legend>' + Captions.FieldFormat_Example + '</legend>',
                    '<div class="formatExample"><span class="exampleCurrency"></span></div>',
                '</fieldset>',
                '<div class="row clearfix">',
                    '<div class="field" id="FormatCurrencyLabel"><span>' + Localization.FormatSettingCurrencySymbol + '</span></div>',
                    '<div class="input" id="FormatDropdownlist"><input id="DefaultCurrencySelect" class="eaDropdown eaDropdownSize40" /></div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field" id="FormatCurrencyDecimalLabel"><span>' + Localization.Decimal + '</span></div>',
                    '<div class="input" id="DecimalsDropdownlist"><input id="CurrencyUnitSelect" class="eaDropdown eaDropdownSize40" /></div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field" id="CurrencyFormatDisplayUnitLabel"><span>' + Localization.FormatSettingDisplayUnits + '</span></div>',
                    '<div class="input" id="CurrencyFormatDisplayUnitDropdownlist"><input id="CurrencyFormatDisplayUnitSelect" class="eaDropdown eaDropdownSize40" /></div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field"><span>' + Captions.Label_FieldFormat_UseThousandSeperator + '</span></div>',
                    '<div class="input">',
                        '<label>',
                            '<input type="checkbox" id="enable_thousandseparator_for_currency" name="enable_thousandseparatory" value="currency" onchange="userSettingsHandler.ChangeCurerncyFormat()">',
                            '<span class="label"></span>',
                        '</label>',
                    '</div>',
                '</div>',
                '<div class="infoText formatDescription" id="currencyExampleDescription"></div>',
            '</div>',
             '<div id="FormatSettingPercentagesArea" class="formatSettingsArea">',
                '<h2>' + Localization.FormatSettingLabelPercentages + '</h2>',
                '<fieldset>',
                    '<legend>' + Captions.FieldFormat_Example + '</legend>',
                    '<div class="formatExample"><span class="examplePercentages"></span></div>',
                '</fieldset>',
                '<div class="row clearfix">',
                    '<div class="field" id="FormatPercentagesLabel"><span>' + Localization.Decimal + '</span></div>',
                    '<div class="input" id="PercentagesDropdownlist"><input id="PercentagesSelect" class="eaDropdown eaDropdownSize40" /></div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field" id="PercentagesFormatDisplayUnitLabel"><span>' + Localization.FormatSettingDisplayUnits + '</span></div>',
                    '<div class="input" id="PercentagesFormatDisplayUnitDropdownlist"><input id="PercentagesFormatDisplayUnitSelect" class="eaDropdown eaDropdownSize40" /></div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field"><span>' + Captions.Label_FieldFormat_UseThousandSeperator + '</span></div>',
                    '<div class="input">',
                        '<label>',
                            '<input type="checkbox" id="enable_thousandseparator_for_percentage" name="enable_thousandseparatory" value="percentage" onchange="userSettingsHandler.ChangePercentagesFormat()">',
                            '<span class="label"></span>',
                        '</label>',
                    '</div>',
                '</div>',
                '<div class="infoText formatDescription" id="percentagesExampleDescription"></div>',
            '</div>',
             '<div id="FormatSettingDateArea" class="formatSettingsArea">',
                '<h2>' + Localization.FormatSettingLabelDate + '</h2>',
                '<fieldset>',
                    '<legend>' + Captions.FieldFormat_Example + '</legend>',
                    '<div class="formatExample"><span class="exampleDate"></span></div>',
                '</fieldset>',
                '<div class="row clearfix">',
                    '<div class="field" ><span>' + Captions.Label_FieldFormat_Order + '</span></div>',
                    '<div class="input">',
                        '<input id="DateFormatOrderDropdown" class="eaDropdown eaDropdownSize40" />',
                    '</div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field" ><span>' + Captions.Label_FieldFormat_Separator + '</span></div>',
                    '<div class="input">',
                        '<input id="DateFormatSeparatorDropdown" class="eaDropdown eaDropdownSize40" />',
                    '</div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field" ><span>' + Captions.Label_FieldFormat_Day + '</span></div>',
                    '<div class="input">',
                        '<input id="DateFormatDayDropdown" class="eaDropdown eaDropdownSize40" />',
                    '</div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field" ><span>' + Captions.Label_FieldFormat_Month + '</span></div>',
                    '<div class="input">',
                        '<input id="DateFormatMonthDropdown" class="eaDropdown eaDropdownSize40" />',
                    '</div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field" ><span>' + Captions.Label_FieldFormat_Year + '</span></div>',
                    '<div class="input">',
                        '<input id="DateFormatYearDropdown" class="eaDropdown eaDropdownSize40" />',
                    '</div>',
                '</div>',
                '<div class="infoText formatDescription" id="dateExampleDescription"></div>',
            '</div>',
             '<div id="FormatSettingTimeArea" class="formatSettingsArea">',
                '<h2>' + Localization.FormatSettingLabelTime + '</h2>',
                '<fieldset>',
                    '<legend>' + Captions.FieldFormat_Example + '</legend>',
                    '<div class="formatExample"><span class="exampleTime"></span></div>',
                '</fieldset>',
                '<div class="row clearfix">',
                    '<div class="field" ><span>' + Captions.Label_FieldFormat_Separator + '</span></div>',
                    '<div class="input">',
                        '<input id="TimeFormatSeparatorDropdown" class="eaDropdown eaDropdownSize40" />',
                    '</div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field" ><span>' + Captions.Label_FieldFormat_Hours + '</span></div>',
                    '<div class="input">',
                        '<input id="TimeFormatHoursDropdown" class="eaDropdown eaDropdownSize40" />',
                    '</div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field" ><span>' + Captions.Label_FieldFormat_Minutes + '</span></div>',
                    '<div class="input">',
                        '<input id="TimeFormatMinutesDropdown" value="mm" disabled="disabled" class="eaText eaTextSize40"/>',
                    '</div>',
                '</div>',
                '<div class="row clearfix">',
                    '<div class="field" ><span>' + Captions.Label_FieldFormat_Seconds + '</span></div>',
                    '<div class="input">',
                        '<input id="TimeFormatSecondsDropdown" class="eaDropdown eaDropdownSize40" />',
                    '</div>',
                '</div>',
                '<div class="infoText formatDescription" id="timeExampleDescription"></div>',
            '</div>',
            '<div id="FormatSettingSetArea" class="formatSettingsArea">',
                '<h2>' + Localization.Enum + '</h2>',
                '<fieldset>',
                    '<legend>' + Captions.FieldFormat_Example + '</legend>',
                    '<div class="formatExample"><span class="exampleSet"></span></div>',
                '</fieldset>',
                '<div class="row clearfix">',
                    '<div class="field"><span>' + Captions.FieldFormat_Notation + '</span></div>',
                    '<div class="input" id="EnumDropdownlist">',
                        '<input id="EnumSelect" class="eaDropdown eaDropdownSize40" />',
                    '</div>',
                '</div>',
                '<div class="infoText formatDescription" id="setExampleDescription"></div>',
            '</div>',

            '<div id="ActionSettingArea">',
                '<div class="row">',
                    '<label>',
                        '<input type="checkbox" id="autoExecuteLastSearch" data-bind="checked: $root.GetByName(enumHandlers.USERSETTINGS.AUTO_EXECUTE_LAST_SEARCH)">',
                        '<span class="label" id="autoExecuteLastSearchLabel">' + Localization.ActionSettingExecuteLastSearch + '</span>',
                    '</label>',
                '</div>',
                '<div class="row">',
                    '<label>',
                        '<input type="checkbox" id="autoExecuteItemsOnLogin" data-bind="checked: $root.GetByName(enumHandlers.USERSETTINGS.AUTO_EXECUTE_ITEMS_ON_LOGIN)">',
                        ' <!-- ko if: userSettingModel.AutoExecuteList().length !== 0 -->',
                            '<span class="label" id="autoExecuteItemsOnLoginLabel">' + Localization.ActionSettingExecuteAtLogin + '</span>',
                        '  <!-- /ko -->',
                        ' <!-- ko if: userSettingModel.AutoExecuteList().length === 0 -->',
                            '<span class="label" id="autoExecuteItemsOnLoginLabel">' + Localization.ActionSettingExecuteAtLogin + ' ' + Captions.Label_No_Information_About_AutoExecute + '</span>',
                        '<!-- /ko -->',
                    '</label>',
                '</div>',
                '<div id="ActionItems" data-bind="foreach: $data.AutoExecuteList">',
                    '<div class="ActionItem clearfix">',
                        '<a class="linkDisplay icon" data-bind="attr: { href: $data.link }, css: $data.display.display_type" target="_blank"></a>',
                        '<span data-bind="html: $data.model + \' \' + $data.name + \'<br/><em>\' + $data.display.name() + \'</em>\'"></span>',
                        '<a class="btn btnDelete" data-bind="click: userSettingModel.RemoveAutoExecuteList"></a>',
                    '</div>',
                '</div>',
            '</div>',

        '</div>'
    ].join('');
};
