function AngleStatisticView() {
    var self = this;
    self.GetTemplate = function () {
        return [
            '<!-- ko if: ExecutionInfo() -->',
            '<div class="form-row row-execution-info">',
                '<div class="form-col form-col-body">',
                    '<div class="form-col-title">',
                        '<span data-bind="text: Localization.PopupResultSummaryAngleInfo"></span>',
                    '</div>',
                    '<div class="row-system">',
                        '<span data-bind="text: Localization.SAPSystem"></span>:',
                        '<span class="label-data" data-bind="text: ExecutionInfo().Model"></span>',
                    '</div>',
                    '<div class="row-system-date">',
                        '<span data-bind="text: Localization.ResultDateTime"></span>:',
                        '<span class="label-data" data-bind="text: ExecutionInfo().Datetime"></span>',
                    '</div>',
                '</div>',
                '<div class="form-col form-col-body">',
                    '<div class="form-col-title">',
                        '<span data-bind="text: Localization.PopupResultSummaryResultInfo"></span>',
                    '</div>',
                    '<div class="row-objects">',
                        '<span data-bind="text: Localization.BaseClassName"></span>:',
                        '<span class="label-data" data-bind="html: ExecutionInfo().Objects.join(\'<br>\')"></span>',
                    '</div>',
                    '<div class="row-count">',
                        '<span data-bind="text: Localization.DisplayTotalRow"></span>:',
                        '<span class="label-data info-displaytotalrow" data-bind="text: ExecutionInfo().ObjectCount"></span>',
                    '</div>',
                    '<!-- ko if: ExecutionInfo().RowCount !== null -->',
                    '<div class="row-datarow">',
                        '<span data-bind="text: Localization.NumberDataRows"></span>:',
                        '<span class="label-data info-numberofitems" data-bind="text: ExecutionInfo().RowCount"></span>',
                    '</div>',
                    '<!-- /ko -->',
                    '<div class="row-execution-time">',
                        '<span data-bind="text: Localization.ExecutionTime"></span>:',
                        '<span class="label-data" data-bind="text: ExecutionInfo().ExecutionTime"></span>',
                    '</div>',
                    '<div class="row-response-time">',
                        '<span data-bind="text: Localization.ResponseTime"></span>:',
                        '<span class="label-data info-responsetime" data-bind="text: ExecutionInfo().ResponseTime"></span>',
                    '</div>',
                '</div>',
            '</div>',
            '<!-- /ko -->',
            '<!-- ko if: ExecutionInfo() && StatisticInfo() -->',
            '<div class="form-row row-separator">',
                '<div class="form-col form-col-body"><hr/></div>',
            '</div>',
            '<!-- /ko -->',
            '<!-- ko if: StatisticInfo() -->',
            '<div class="form-row row-statistic">',
                '<div class="form-col form-col-body">',
                    '<div class="form-col-title">',
                        '<span class="statistic-title" data-bind="text: Localization.Statistics"></span>',
                    '</div>',
                    '<div class="row-created">',
                        '<span class="field" data-bind="text: Localization.CreatedBy"></span>:',
                        '<span class="label-data label-data-user" data-bind="text: StatisticInfo().CreatedBy.full_name">-</span>',
                        '<span class="label-data label-data-date" data-bind="text: StatisticInfo().CreatedBy.datetime">-</span>',
                    '</div>',
                    '<div class="row-last-changed">',
                        '<span class="field" data-bind="text: Localization.LastChangedBy"></span>:',
                        '<span class="label-data label-data-user" data-bind="text: StatisticInfo().ChangedBy.full_name">-</span>',
                        '<span class="label-data label-data-date" data-bind="text: StatisticInfo().ChangedBy.datetime">-</span>',
                    '</div>',
                    '<div class="row-last-executed">',
                        '<span class="field" data-bind="text: Localization.LastExecutedBy"></span>:',
                        '<span class="label-data label-data-user" data-bind="text: StatisticInfo().ExecutedBy.full_name">-</span>',
                        '<span class="label-data label-data-date" data-bind="text: StatisticInfo().ExecutedBy.datetime">-</span>',
                    '</div>',
                    '<div class="form-col-title"></div>',
                    '<div class="row-execution">',
                        '<span class="field" data-bind="text: Localization.NumberOfExecutes"></span>:',
                        '<span class="label-data" data-bind="text: StatisticInfo().TimeExcuted">-</span>',
                    '</div>',
                    '<div class="form-col-title"></div>',
                    '<div class="row-validated">',
                        '<span class="field" data-bind="text: Localization.ValidationLastChangedBy"></span>:',
                        '<span class="label-data label-data-user" data-bind="text: StatisticInfo().ValidatedBy.full_name">-</span>',
                        '<span class="label-data label-data-date" data-bind="text: StatisticInfo().ValidatedBy.datetime">-</span>',
                    '</div>',
                '</div>',
            '</div> ',
            '<!-- /ko -->'
        ].join('');
    };
}